#import <UIKit/UIKit.h>
#import <objc/runtime.h>
#import <QuartzCore/QuartzCore.h>

#define BACKEND_SERVER_URL @"http://fi14.bot-hosting.cloud:25981/server.php"
#define BACKEND_BYTES_URL  @"http://fi14.bot-hosting.cloud:25981/bytes.php"
#define LICENSE_KEY_STORAGE @"external.license.key"
#define DISCORD_INVITE_URL @"https://discord.gg/nMQaamDNj2"

static NSString *const kEmbeddedExternalLogoBase64 = @"iVBORw0KGgoAAAANSUhEUgAAAH0AAAB9CAYAAACPgGwlAABf+UlEQVR42pX9d7xdV3nnj7/X2u2Ue24vkq5kSbbkKtkWBmODbSABDCFAwEMJZRIygfRhkl8myST5JpAyk0zCdyb5pkwSQnoCmUDA2Dg2xjbuDduyLUuWLFm93N5O3Xuv9ftjrd3OOVcier1sSVfn7LPPXms95fN8ns8jwNEgML80IBBCoLU2PxL2x+lf1vklBAKNRoA211nv5eaVfS7fdR/Z7xT/LJLPKFw0+6VzrxGi60W564r8G+2/pdfW6UehNWiFRuU+V3PhX3rdZ5Y8rfVfqu1H6L7PGp1/drrnUeh170UjwNXnu7n+lxC9N5FcI3nQyQ0Lsc41z7OR0o/UF/h3ipsr3ahinc/Lb8RkA8niZkLaB54svEJo87tWyv5MX3BR+3/jbKF7Fr2wOPm/5g5A+lzXee157yf7N/f8D77Pw9L91qvP7hf9riu69oqw30mYj9Pd75e9Oz/ZYMn1tX0wQq6zyXInuPs+hMgtush9ZnKMNEILIE7vM/uKvQ+49xEJ+zPdZ/HPc6DswRF5o9XP4uV/ll+vvkc9e60AV4u++0akz0HnTlC6Q3X+RJ3PjJH7gt0/Fb2LpOk5rf3NWLL4dt/quO/1hRC9ny+SRZZ20ZPFTl6jso2kY9CR/V1n/3YBUy56XFD+G4jzn+6Csctt5MT6CNFl3HTfN/daE50/6et4KJ0/sWahtdB9tpIg2ZdF4yXO93X6WwDRu4F0z87ud5PdLscspk4WOP+5QppFThffyZ14DcoufPJabTeFUOY09YQbfe5Z697zdV7jr/t8K23v/3zOOhefJJss/U33/Rw3H7Qlu1PnzLnWXQ81PaCir0ehj4nr/Y4yZ03y11b2+to+5O69JdY1WUX/rHLXFTlfTdfr7GmXvl1kezqlCzoEFYJ07L1oUCpn/nVv0Jm/v/NZA5F7luuEtMlG6bFyItvAhbBG2w2iLxxkuj03VbihQrDY9Uq9jpmSWYzYd21E5st7/FL3A8nvYHG+UD13agXgdL1GmtNccF0ChJdbA4nWdhM4dhOEK8asWzMv3DJax2YzaNWbUfQJvnSPNRK931l3Zyzr2zXRbT1TUy/On1XkLu3mP0rnI26RPXid35VC9PXh+U2ge06lKAR3WpNPH3LfWfTGE0L02Yy6f5BWsCDSnlrPLLoOiyZcOAjp2oeuzN+FQONk/l149vWx+Zk/BuFi8SmqyJ56nVmrfCCr+wSPheeRz0B1TwQjeiKB5Px32QDRe0IL183dh3tefyNyMahYLwgRXYvQZRpEV25cMIUi2yxC9pxE3fXabMPp3AnuXnxRiOSFUzavjmJ72u3rpG8fX2LiHWMhhAuqA3HDXkOmv2vVNteQSeBoroOOEShjBawlSw5CEnkXDHK6GubaiQtNMAG9zgnPDpdeJ/ilT1zRhbuYu/G0sBGi7om2de6QiZ79x3qbQKwTLRdAExA4uS/R5efT9+T8tehz0oUNxLCRtrQLq+3plI79HiZwEyLz42m6mJp+DVqgVcdYBjRCKxvjuOY/HYJqIaSPjlvW1Mf284onUus+q5Jsorw5TqxDPkLPWUGRX8QuS5sCYgUUINnzOrOqIru2m+4s3WWmRYYI6b4ZaH4jXACt0yJzGbkHoPMPQkhrZmW2AYToAt+EiaAL6VWyOezP003iIYS0+0yYxU8COiHRyUJLNwfIKJACIQK0kgjdSeMBoRVat4270BJkYEw7UW6hcie6Xz5fSBFtwKnJXFEBZhNZBN8db3UF1QWTn0NSs22juyEUVxdOqO6fTvcDIgqp1Dq+vhf4ID3paTqUnFYd2fTJ6QFmRN4V5KyBQGZpopDoxD9L114zOanm+sItG18dt9HSsZbbBadsn3sb4qZ55Fobf65idNxBCGX3sANxaBfNfB5Rw2YAed/e9XySmCKPAqrIfDNtMwKt0pMv+mT3/eDVftZ5/QBdd0fvFKNl3Xf1e0MN0QfuhC5gRBfNf7JgIoNvhVM1flOZE5ffLDq1GDI9rQhA2hOtNVorhPQMPiAchFvJnX5t/bj1x8IB4YNj/bgTINxBiOvoVpj6auK63Yz2FGkbuAlpfL/WCOGipWtMfbIQQmaHIl1styvOUan/TwPK3PPSxaQ7A0jXgXZ7vK9O7kUUski3AIfq3AvS9elFtPSFUGYbyGldhFRFGpzJzJXk8mmdnI58hJukW1rbjSDNw7MnWWN8sjnZ1hfqGO1UwKlYC+BkZlVr47BUJ/ewY7R2EOXN0FlEhCugQnO/TtU8F9UBLdFIc30hEcJBYwsxPS7QopdCGpegYhNMekEGQCll/j21Cvakd+XIInG3XVdfHw3NVk0L0VXGEAacKWBAXTnx+tBBV16a+su8SZG5WE72yRJkIYATOjSmU+TSJunZPWNvXnj2rb4JpoS0D7acBWrSt5G4/bMTIKSH0DGoyHxT1UGrDoIYLcsgAmOivRF0aTMinEPHTWPuE5ciPYR2QIfpQ08BrRQGlpk3Tj5fS2RtO6WJXTRP3I+OVjIkUOsMQ9AR0q+ho0bueqJPzVGsg6B2AURpTUMVFtPVWltrm5gAkZZJM7OSlUyF9MAJ0FG9f7UtDciKOLpOAxkBSheLG2mK5mamULr29LrZBpF+9rWlB/4Iwq0inAEUnrm8U0KouvHDThUla9b1qrRqhg6N2XYr5pqiDaoNwThSR/bawxCXoDOPlpEJ/rSy6ZxGuD46buf2eJw+cJ0EZ8I1dq28mW3f+7MsHn6SRtTKnUPrv6VjLAECpcJiZW29A1cArXKvsPGS7qrpdQXhrqaw6F3ZVs+pF32x93QR05OqbHQrMyvgeDngROVSte6A0AEnMKdZADKwtaGaNZUa3DLCH4bqJYhgFBmvobUgjgTEArxRKFfwKhUqZY+BWpVS4OFLiataODImxqMVKeqr8zQaHdZWl4kWjsDaCdANhBMjaaPjNlrFxhI4Pv7wNjozL5gTqyPzPbUqwsHCs+YfRDCG8AZRKyfM486necmzSMy6ivpG3IVFK2AcXSddqzTFTuslXe930+JIzp93x3O9SIA+D0ijs4WTeSJDAoS4aJR9IP3gVM8srHAQTmDBEB+cqnER3ii4NURlE7I0jpZVFEOooAZDUwxNDbFlY4Wp8RIDJQfH0WilUUoQtjp0Gi1UFOG4ElfECNXGc7fhixAdtVmqX8fK0gLHD7/C3InniBZOWbdhcnMZDJlTriJ7IKSNTbrrCcriLx66s4juLCL9AKXaXeuoioCWcE3GkFT0+oI0uUOSC9a06OcOuvH0FJwp1sD1ehDPeWvjMmfC3ZxfVllEKz0QvvFXKUaOjYjte6RnzKI7YH1yCS0DcAcQwSRicDvO+C5iOYESA1ArM7F9jGuvrLBlg0vFhbW6ZuZsk7MnV1hdXKW5Voc4ImqvocMOnuei445J4VQH6QhcR+AQMzg4QLUkcUREMwxpr61x8tVXmDv6HXRzBnTDpHQCc2JV27gSHVngJ5cmJm7KKZufqcimaW0L/mQhdQo5CwFxJ7fo/cvWooCf5AGhLpJHH2shBF7hwOlCJibOWzHr8RSJT08W3Jo5s8MihLA+2ymhkRa3likipoUHThnhVu2CB+CPQjCBCEagugNd3Y6ubsa7eJLXva7E9ZdJqiXNyrzi+ImY2dNtFs6toloNPCKbCUWodh0VNXFQEHcolXw8V+A4LqCJ44h2q0ljdYnGyizEbQLPZaBWxSsHRMJn9uRxZo88SWfxVdB1pNCouI1QkV1EmUb1yJKFYT2LHXWM6QV03DYbPUXj7FOUnjH5quvfhLD5miri9t2VPK36kloyDkRaTfU0/ZJ70T8p0H1rOl0ATBqMmVxYOAGo0Hyw9BDSN2Zeg3ACtCyZSFzH4I9lsK83gqhuwRnYjq7sIB7YinfxRm6+2eeWazSegkNHI44f1SwtxBCBG0fQXqO5dI7W4knCtdOEq6cI12ags0zUWUHHEVJoPM+jXPKp1AYpD4zgl0fRbg1ZGqHZgZWleZor8wgd47kaxw8IahuYnz3D3CtPEC0fQbjanszYnGQhM2DIKZvFVjY4zOfoKgTVNLGCzi062ub/qrewpCOzhFKkaZ7WXRune9G7jbZx457OArjEv69Hd8pDAqKL5JL83QZuwjVfQgbmQaiOWVTpm9KlNwpRx+bCZahst6VLGyG7Q4jqNM7YNURDV8HUJG+5dYB3vVbTbsfsPaQ5eUITrsQE0keHbZqzx1g+8jhrRx9gZeYg7dVzqM6qPTkiSyPT+nqexKlxHChXBhgdn2R0civl0e0ob5RGM2J54Sxx2ESFq3iVEfzhrczPzrL0ygPocBGRpnbK+uWkmBIXgi/jvjyIW6BadsFigzc4JeMG4lbmZHU+d+/6c4HlQx/SZh5kU3lAqHjSRYLF96y3zMGholBCLpp/a94dHyFLaKdk/ilumBMhHQOauEPm9U4AThVKm6C0AREtgTeIGLgUajtRY1cxfeM4P/YewfRgxBMHBc++qBBtgas89OoCS4cfZ+b5r7N8/Ami+jnQHYuhJ2udQJvdbFaR+WHporUwbic2FCk/8Bkdn2J800684W0024Kl2RO064ugY7zBKeTYNazOzVI/cjeCtS4msIDUlJNmNtpSsEQhgMsqjVrHBlPIATVahdYVWishXHNAkusX+AK6N7hON7gygVyeNtyvmns+Bmu66fLFgAQQEZ7x39Kz5szi1TKwUXrJLLA/DNWLobwBwlXE8FWIydcST2zmHe8q8ZGbYo6eg0f2axZOxQQyQK2uMfvcXZx95v+yeuoZk3dLgRA6Zb3ovNnrqvD1Mk4zS5dkDhoXHUegIyoDVcamL8MbvIS1pVnajUV0HOL4A7hT17HWqdF69S4I50AmEG1kF8jJfG5aqnWsBUoy58AcmLiVpm4i2bBoE3gKx7qR0ATOylxfBKMQ1U3Vr6fUrYvf2UTvfpbM5Qv/opulofuCMaJQcpUZI0UmqVYF4dYsftFC6DZaBMaHeyMQTCG8AbQzgBy/GlHaQDx6LeVdU/zEDzhcvVFx5wtw4oSChotsKRb33cfJR/6G1ZNPA22EjCFupcFSD5smXwco1B505iMTiFarrACCRggH6frESkLUIqgOMjhxMdIfotVYQ0UN4rCDHNhEWLueztx+qB8C1QTVRji+2Xw2JxdIAyFbHy9sHUBbQMtAvA6ShKETpQcmjhVahwbI0bG1XDHCH8ktui0hW7g5+9J54qzwtehma2p6EbN18PWsXCoyX54AME4JZMWkW44lLYTL5uFKD4INyPFr0bFEyypy7BrU2G6GXr+NX3i/JnAEX34cVs+FBLpENHucU/f9KXP77wSaCKkhWjOnIPVZIqvgpbi16L33NKjJ1fR1jteuc9x3bQojwglQ2mQDpYERykNbiCNFFNZRYQvljSFGX0tndQYaxxC6aYk3ZvGTWr6wLk/rEHAMlKzMvWSuO0SFDYg60G4CCrdaRsct4taisWYpvBrZ4lU/XrwqUsfTPL0rTi9yWtfL1WVXfVxmEWiStkkfnBp4NbPw0kU3TyPiNlr6JlIf2o0evhrpj6OmXkv1us185qOCuWW440kNi4pS7LK6/5u8eu//Ilw+ivQEOlozqY/IlxZt5Gz8VvY90kqWUyhrisRnoi1Mq7LqX3I6u/kFQiClSxzHSMejVNuI1gKlYzQOOg5RtavQYQOhVtDaIdYatGdW0ymDWzJWxHFx/DIShXRcEwcJgeP6eJ5LiRZTQw5bNlQZqA1z6MCL7H3qHqL2irVqRaBMSMdmA3F/umpKokhpEl30pZ6eh26Omu4l+SVkBhnYGnUArg/eoNk87Vmbujm2YOLBwEacyV3EeoTaddP8ykckr57VfPMphVyBWtRh5rG/4PjjfwN6DeGEqE7dRqFJmiMQ0jVlVWVBEhQyRa1UDkOQWdIpZGr2Za4kav6k7J5W1oFplIYwBBWGyGAA6Xi0G3N45VGkP0zUWibWDvHqCZDD4G3EGdxAtTZBZWCQwaEBKtUy1RJ4notfCsziulAZLLN1wyDbJypMDFcZG/KZGoLV5Qb3PrPKN++9n717nyPqrPWnoFmI2xx23UvczJl41/g40bcnQ/cwNL5L3rbqoKWLEL4J1pwSQrWtLwuM35IBWlRwKtOIykV4F43z0++VHDmn+NajCrHi4DcXOHb/7zP78j1IN0Z3jN8SKeqXFDUsJgAIx88hgG7umwiE45nfpcxIkcJF4aBic1KVNetagcLNpXkl/ErAxRuGGRoc5OzsGmeO7ge5gUhuAFnCH9/F1OQkWy7ayOZtE1x52SYGa0PUqiXKviDwwNEhvjDgrS8FWsWMDZXZMlUj7HTQWjM+VmV+YYW//uor/OOjDjNHH2H+xa9C87jZgCouUKJNtdHJNneerNKHROcmJrpIkcgT+XqpOUWTkUPiEj8oTFHB5JvKpGg6gmAS4bbRcQiyjBi6HDF0FVGlxqc+UGZmWXHPIwp3RVNtz3Pi7l9n6ejDBqhqL9iFNKCH2aixQfksIJTQooRwkY6HkMKYbeGA8Ijx0MInxmQOTlDFKw0Q+BUqtSHKZZ9SpczoSI3a+CCDozWmhipsHR/k0o01XBWy9+A8X/3GtwlKY9x84we5fvc048MDjNYcpkbKjI34VAKN75sFbTZbqLBtn40gCFx8T+JIiVIa3y8xNTZAvRVRqfhUyx533HuQz/zZAQ5xNVMcZPXQtxDNlyFcMWXkxIYlnHwZGGKmiqzPzjFkdS+e6hq6kSqQazNenOhl1AhhmCIq7sreZNoTkBIDVMucbm8IHTfNAgWDCFmG6jac0SuJytN833uHCZXi7gcV7nwHt7PGiW/9Kssnn0K6Maq1aE+3REjHfFkhcNyyCYqka4szPlr6aFEiEiW0LCPcAaRfpVytURuqMjw6wuT4IOPjg4yNDTEyWGag6lIb8AlKHsO1CtNDDlMjPoOBYHTAJWzW+ZdvPM9f3XWEJx/4IvWFFS6+4UP82Aev5e17Bqk3mjYohFa7QbujCdcUUWyeqCNdlFZ4rkRKiZQO0hFUyh5Dg2X8wKNWq7D/lXP85p/v458eXGNk15vZHh7n0D3/QLz8LCJcNhhCkmuLrHFD28qakBIdxzYe0QVuQz4Zd3UKuPTpT7SMGlFgdvZrUExuxOnqWNGGaYKy0KuDqGyA6jZEZTPR0FVc9T2T7Niq+Zd7NJxexY3azD/1OZZPPIF0FLq9iHA8HMdDugE4ZRQeSpYI3RraqSD9IbzKOLI8ysDQBKMTY4xNjbBpeozNm4bZtqHM5gmPjaMeIxWHilS4KOJOiOq0jWmPY0YHK9QqHo1WSOBHOK7LnXc9ye/+1dM8c3gecfZOWotz7H7zj/Lbv/BWrrvcZ3G5jusYznynEyGkS7XqEMeKKFZI+wwT9pcjBb7n4LkO1UrAYK1Ms9nhd//sYT73pVPMtrZy8dtvJpg7zYG7/xZWHkWES2bBE1ejc8UWyyLSaIQObfQvMlCquztBg1tskOnTjyVyEby26BBxgdIshEkXdEqOUJZlavHicAXcisknS2MIIZBjWxm54RLeeqPLtx7ViDNL0Gqz9vI/sHDoPqSjUO0ZZDCMdgaI9BCURvErg4yMTDE2McnU2AiTGybYctFGNk6OMjFWZXqiwqbJEuPDLhUfPGKkVhAr2u0WsYKoowijGBdBhMbxXWoDA2gNkXAZGi7z4ssn+c3/95+586mQgY0bKM/9FUtrird/4Gf43V/+QS69aJDVeoeRQVBKE0UxnuMSK5vjS40rs65cz3XwPIdKyUdpTa3q47oe9zx0iF/9g3t56pCDf/Fb2P3encSnZnnpnr9HLN2Bbs9nlO48/Cp9yzeQ4AxAtGIjd9WXwJpn6Lp6vW7SvgdbFLiX+RRPaFvPFbn2YdcHd8CWIi1xsHkOMTRC6FZ4+3Uuz++PmTm8RtBuwsx3mHnp6wgnRjVnkK6PVh433/of+MiHvx8ddti6cYjpjeOMDgUMDnhUSh6uk+s2RRF1YsKohWpCx35XpRXgoITZ6o4QOFJSC1wcaXL1cslnZaXO7/3JHfzpF59kKdjN1t2bOH3vf2W1WeFjP/Fpfvu/vJXhqmStbqpwydOqlAMc15x4KSWOY/xuFCnLnYc4jmi2OrQ7EbOLIf/vFx7mr7/2DKJ2GUO738CON21BnV3ghdv/GTn3j6jGmaxzVshC4IY/YjMlz5rzToFJ21OA0YVeNt2XyVrgWPVr7s+X6jUWAnUtn9w0HQinYhmlDbQ7AHGIlJKo6bFzxwRRQ/DySw3ctTl0c4Fze/8JVAvdOmvjSRfH93hu3xl+cazM9735GrRWxFGM0iaFUnFEJzb3pHQSekqEI5HSNCvEkUrRNjRIKQhKPp7rIITG901AdPs93+F3/uRunti3zMhVt7Jz4xYOf+0naHuX8dnf+Sn+y0f24HuCUhAwWINWJ6LVbNNoNFleWWVhcZmlxSXm5+eZX1xmfmGVxeUGK2sdllcazC83qDcVq22P0uBFvDLrU5nYg3PJzVz1PcOsHqvz7Ffuxpn7S+LVYxktvLuTx60Z1FOtocNGjoXbq7Shu1VBtE7MexeqpjOAXueKB7qAxukCOKMtnJgQIAUC4iZaGE65iOrgVdGUcSZ2cvWuUR59uomencFprdA4eCfhyglkNIfSEcKtmLTOrbC29Arv/dE/4c4//1He+uar6EQKx5E4acKgERakkTbCkVKkCJcsy3WTTaXh8Kk6v/EHX+MrdzyGU7uUHe/5BCXP59AXP01l8jL+16//NB9/x3ak47D3hUP87T98mcXFBRaX1lhrtFheXmFlZYV6vUG73aTT6RDGGvCQbgXhBgh3AL86iVsaJvYnmPSn2Xj5FSxWtnLjO4ZYOF7n2S/dh3vmj4kWD1psvtPVCGJp3EJaaDbOne4isziFYQuEal1sYCxU2hIznkOkdMrlllnrLjqt8aKFuQkRGWgz4YgndV/p4QSjxHqEPddv49ScZnbfqwyygKgfZfH4o0hRR3UWDV9dmIhcOCUEkokdF/P3z7S58bo1KrUq2vpO33f7Lmaz1abeqJsTtrDE/MIyC4srzMwtcnZmhbnFOnMrMW1Zo94O+M7zRxm69D3Udr2WoarD3v/zs7iDFX78x36Ij926lTBSSAX/56++wle+8lWkxASX0pxC13VxPRfPH0QIDyVctPAQThnh1dDeGCrYiFveROhO0hq9nLErJ3jNroBzh1s88fcP4539HOHcC12NHzLXAWPXRIXgDtoqXtMSlKJcl0+U1Q764ChuQqIXBd61TIMzoeP0rYXcL2FwekPGZ1shHlMBst2iKrJ5MybqDjXe+CQX7Zjm3ofO4a2exCkpFo/chw7XoHUubTIUToB0y8TOMBsvvZUf/+wP8YFdZXS4QqsVEvgOnufy4v7DvHzoOItLq8wtLHN2ZpFzswssLCyxstZgaXGJlZVlWu0OWkNsW5JEMIRTGqNUm+KiHddRveL1bL75ckrtJR7//Z8iis/y6V/8LX7uB69EacFgrcwddz/KK4ePcenOS1hda9JsNojjCMcrI6VD2OkQa0GsXWJ8tBwAZwRZ3oyobsYb3YE3vp3S+CiTO1zeeQPce1/Io3/3BO7pzxGefTrrl0tRNgsbu37GtkHl+Khx1iWcHLQc/Kx7umXALfQ357otkyKDzrchpUGCKQvKydchqtPER+8wQZzFq817EotgOG/S8YjjKpdet4dTMzGd00cYZI323EGa8y8bsx43DTYtDTlS+iWi8i7e9cPv45bLy+x02nTcCqgYKSWnz87zX3/tT9j30ktopQzSZsuYUgocRxJHEZ7n4AVDputFVtBujWBwGvwp4oErCHZdzS2X1ph/ZZ5H/vi3iJYP81Of/W1+8WN78ERI4HssLq3y1Tu/jedKGsrk5HEc4/gDSLcMwsCqCBfhDyP8EWR5HPxRnGAMGQzhVcsQzOFE85SOwX3Hhnnw24t4Z/8H4ZmHDGydlFvTTp6khlGGuGXyDWfAZEedFVub7+ksyYkmFBVCUiWKrKokCgl9oeOx6AmNyV46iF54ySo3xMWgUUUp50sj0FoghqbZcPE2ntl7klI0g+Ms0zz7hAn0OgsmKrV8d9f16egJdr/xTbzt1ikud0M6CoSjbZAm+eevPUAUx2zfOk290cb1Atptw2AJo4h2q21OiwgItWvr96MwsBVv4jLKG3cwdskGbnuXx1PPdvjXP/4D9OkHeN1/+EX++8+8BSeqo7TE81y+cc9jnDh5Bs9zUSpGCMHY6AjzC4u0O02Utvw4HZscQrkoLYhiF6UMGhhFgliVQFRAeTB5FV77IcJT95lqZL6+ntjeBHJ2yoYKnvQBRKvWj3t2PeKMANMdv+tuUYIeMZxuqY5ck3tB2EajW/Mpnp4SIAtIna19SYmKfKa3b6Xedlk5eYxK5xwqPElj6QwiWjGFEi8wftwtodwqwcilvP+jr2HHgGZUxHSEQGpFKQh47oVX+M5zLzNQ9plvCqSATqdjKnm4OF5ApTRKJGtor4ZwyrjVDTjVKbzRzQRDA0hXU/PqPHC/y1f+19/izN6F3v4DfPbn38eA02KlJRio+hw/eZZ77nuMSuAQKfN8RkeGOXlsHycPHUCUBi212wdRMs/CqYDj2VqAqRcICY5QhkWk2oiT3yJaPW7ek5j0nEpUuoQ6MhU0dwzCZQiXUvaMabDsdGVl+fZv1ZN0uX27VXORvOnH0lkDnc63LCXhc2g+XPhFoSCbIgnHB+0yuXUrr74yg1w9jOut0Vg4BlETwiVLjzbNhI5XpsMGbnnnW7nmmlG26Q5twBHgOA6NZosv/et9qNj0m0kB5UqVThiyvLxMJ1KEsclt4zgmCiMi7RLFDjFVIuUQxS5RVAZVAunjNu8j8jbzgU9+kndc4zE3X6cUuDiuw1fveIjllRWGhkc4d26GykANFa5y9MirOEHN0JsMJwyt6saPtiPjb22ErVL6U1dzh/Ss0gXFHnbppEUlww72DT+hs5gFdyoydOo8ByBh5QjfwOCF7pfUp8t1NeGEbeoXws2xPfNFG6f4gUIZDFzHNno0zXsqjvBGhhADkyy9tJdAzyJ1RHv1NELXzUNzyghhyqMxVca27OYdt72eS9wYX4dE2pREy57L1+96hOMnz+BYxMtxXEpln0cfuIel5bXUFJoMwDdm0SnZk9GwQlEdpA4hWkFEa2h/guHv/Vl++aObWFtZxfMMTPr8vsM89tTzVKtVGg2Tjg0PVXn0occQTgnVnkcnHLhCrmwzoLSk62bkjqSHLY2/ZNHKyhwRxa2BP4zGM5VKt2RYtLplJVXIUjdhmiJxBoyladf71E/soncrGKR0enuaRcph11mfGrndmDI4ElquSBv+heOhVYmBzZeyuFonmjtAUOrQXj1D3FpCxHVT8nQCkC7SCwjdad7+oXeya+cAF4k16h0o+Zog8Dh1Zo4HHn6GocEaa2t1Go06k5MTHHjpKZYWG7ilij1dLRvoqpRLhorMAimDkGmbVXhuQLjz4/z8T97CFYMNluuCciAIQ8Wddz+CUhGeV6bRXMYPSpw7c4TFxToOIbGOs6bKxDrmy5vp35OnLI0L0zGxitGRBsea6W5tO6cCwZRN2YSBZKPVtPhkNg/FFmfpgmpAvNoHTDP34xrPkeO3JepvwrU5ecbExCnZYEOZiDJum+v5I8bXaGUaG6WXPnDhD6FbmmB8M8vnzuHSgnCV9tKrhk6kIssYkWbBdY2d176eN3zfHi512oSxMh0pNk/92jceJoxiHCnodJqMT4zTrC+yb/9hvIExwuVDudbf7v7w3EkSjuWvCcT0m3jXT/0In7o+YnElwvckpcDjkSde5KUDR/D9gLW1VaJIUSlJ9u17CcfzUc0FhFuy2JVMVSW0/XPS/q2VzKTJtERHLrgesjLA+MggSwtn6LRWcocHE8kL32zUaBWilax7JmkiITQM474yJutzHtw0NdNWGE+61izJHOskxxF3AnvQPUN5Sjhx0odoLYcemRYlHXfAHaQ8Msnq4dPIaBZBiG4vWxaNbcyXLrhl/Mp23vrhd7BzVDKiWrS1QMYRQ8M1nvjOPl586RC1gTJRGBF2IkZHxnjowW8RiyqidcpiCEGXilNOUAhp2KpIhBvg+Jt538//Aj/97gpidRnhOPi+w2q9xe13PUin06FWG2BhYZGBaomX9z9DsyUQ0bzhBQgP7dgAzivheGXcoIYfVPEqNSoDw1RqI1QGR3DKNUbGh9k2XcMTNSJGeenxb/H0t/4CKaSpDySVSiHBM3WL1I/HdcPS1dq2U0VZ65PW6yr5dWt5ualgX16Gy/TeZM38lpKUBiyWlC+Eh/ZHzWLniwLJrpIeOo5wasM4aML5wzjxClqDikPzhWwtXroeYTzKjW/5Xq6/6VKukGustCKqZQ/fc1lcXuX+B5/B9xy0htn5RUZGRzmwfy+nZuoErqLVWTE5s8ydrDTfdTM2qpAo4aM6o9z0oR/hhz78Gja36tQVDPpQKpX4xjfv58DLhxkbG2Fubo7llVXOnZll33Mv4QxuoVyeojIwyMjYBkbGpxgaGmVkbIyxiXFGxicpVQfxy2XGhgeoll2qgWTLZAkPxf3Pw7/tq/PM3V/m9JNfh7Ce6/gVCKdiGkBwQEqEV0VHTWNFEJYwEXb1w+k+kmvriAcWSqtamSZ8u9jGWrkZfVcYPy+Q4JYs5u2i3Sq0z5oWplQ8N5EFcfEqVdYW5tBrJxGeskzPOkLHCOkhHR8lywxNXsqbPvJOrhiIEa0mfskHrSmVA75199Msr6wxNDjIqTMzKA2eo3j2+RcIXEl7+QRa+GjhG4EBWUY4VYRbxQlquOURQmeASFTArTI4PsXGoWF2f+j7mUBRkQrlGCrV0eNnufPuR/F9l+XlVebml3jzTddx1eVbEZ/+GUbHJhmoDRAEAVI6RApMUU3jSIijGM91KAXGLQ3XwPfgrsdm+d3bQ046A7D/Thaf+ypSnTDEDx1bYZBcDcQpmwJU0pUjS8ZdxO1Cbb0Y+asuYbmuRmWtDYmip6sRnTYKaJVE8Z4V2GmbnNqZMOZHSAQO+KO2j9u29iTIWlgH16GxMIuIlpFeyQALyS6VHo7n0VGDvO0D7+S114wx0V4kkpKyaypaR4+d4ZnnDuJ5LmEUs7ZWRzqSu+65l6W5Du7gIJWN1zAyPk1tZIqB0SlGJjcwMTVFbWyU6sgw1YEqsQrYOFJhIPB54WiHJ54/iqcGuEi1iQBPCJqtDn//pW9wbmaWWMVMb9zIj/7H9/GGG67FcVykFHTCkCiKiCPFWqNJvdkhCjXScVBaUC4bTD4ouQzVSjx7sM7v/M0pvvlywPY3XszAM9/kxPNfQzSeNGIKTmDk1USOOo6HUM1MG9apGouqOllNpIuqbrTsivJhvYKdArdXCD9/8o2Z11IU+dNaGXPjVCEYMTczeDmifsLwuGRgFStKEIUo7dNZOouOV3FwiTprafDjuB5hHLDtqj284d3fwyVxm7DTploNiGNNq93mq3c+wNzCIlJoFpZWGRkZ4rXX7mTP7ksZm5xmZGyc2uAQtVqVciWgUg7wPInjCCqBwHcEZV/gAM8cXOK//1uLu7/4edbWXH70nT+OIyJaYYRX8nnkiWd56PG9COBtb7mBH/7IuxgeqrG0vEYn7BDHmnY7RGuNlA5aCwLfp1KWlAIfISVSaMaGAmaXFb/2f/bzF7cv0x68mKvesZ3Vxx/jxLf/AtF4AB0bPqFO+/LdjMKtQ3TYMt0//iS6s5ABXjnNuhRnUaooTtitTysyHXu3KN+d1xvvaoFVseH8JACMDqEzhwhG0E7FYN+lSdNWLHyTMiW9XMJDrZ01LNm4TRw1rUKTg/AqSGeat/3gB7lsY5lKYwbtGIqV43o8/OgzvHTgVaqVMq12xK4rd3Lbe97CRZs34roOUui0xh7FESpWIMJ0g7pIyn6Jc/MNPvuXL/B336khZh5j7fl7uOU//082TzmEnTax0rxw4Bh/8493MTk+zo9/4t3ceP3VhGFIo97Ecx0cLcET+K6T1vNd1yEIXCplD0dKXKmJcfnS3af4jc/v5eiJAHnltVz/tg2cuvtZTt33h4jGvehYdGEctn/fxiI61QAyEKuxjsUSqvCG0eG8FSruauToFhnVfaS/e3rV8sX3JILXdgcKL8V6aZ2E0rRpvHeGwB9HN85AaCpvINBxBxkuI6XZLCo2rE3H8wnDgD1vvImr3/Z6NnaWCeOYgcAHJLOzC3zzvscQUjIxPspNN17Ddddeju97tNstGg2VknQSrp8QEt+TuL6hJgH8wzcO85t/9SInxE62BAsceepPGLzmQ3z4tj1s8ecJY8nyWouXDx3lbW++jp/65G04ttXJ9xzKpRLtTkgURjRbbcIwpB3GNFsdmq0IpSWNdsxqPcKpTPB33zzDl77yDO74Tmo37uKKGwc4ef9BTt///yFX7rTyMiLTlE97+hXEUdbyXJ5Cu0PQWbJ5fE6DHoUOFwwhoBC5iy6ATWSaPzqnI9erB9nFtsixLnRSVk1VIiqm/l271DYEuAh9DB03UjlOGXUQSQOjitIuTi1LVAY28o7/+H52DmrclQZ+yaETRsTa4ctfu5fZ+WVe+5pdvOvWN3LR9BQqjgnDEMdxcBzHnnZScqJ0srrBgaOL/NafP8ZXH1nC33odO6fGOfiP/w+hexGf/MlPct1Yg3q9w4qKmZtfJmwss2FqlL/4q3/h3OwcjUabtbU1lpdXWF2rs7yySr3Rod2JaYfQjgRtFdCJA5RToxGVGbtoD3VnE5VtN1C7YitXvdbn0D3HOX3vnyOXv4aKk1653GLbUnYWwWtDM0skV/I4OroLdlVdEqQi1/LUrU2j+0l/n0ddmzjTeU90V+2HaBFAcxZKk8i4jmrPmx1m24N11Eg7VpOyreOXiEKfm97xLi679nJGVhbpxAo/hlhp9r/8CkvLa/zgB9/N6197JVPjQ/Z7KmKlUHFMFMc0Gg3a7ZBGK6TVjqm3QmJ8XjoDv/1Hd3F2wWVg91u45Npt7P/L/0HzzCGu+MQfctstIzRmT4OnGBuu8u0HH+O3f+ePaDZbOK5BGWOl08KkFKZZIs1MvCqOV8XxHfCHcEvjDHgbqG3YSXXqClqDHtdfJ3jyq+c4+c3PI2f/BhWGWTeBNNo7JpUMDHfBBr/CrZm4yakZurc6Y5k0RurEcoMy/TrR5bdVTlQ5weiLiFyXxEhPE1w+KFAWkIhTkoQOV2H5JWP6B3ciRq5EDO6EtcM2D5coFRnZD2x+LiRxDKMbtvKGD7+fadGitbZK4GlW64rV1TUeffQxHCF58sknePyxR+h0IlqtNiurdeqNBmuNFvVGm0YrohNCoxURySqd2EFWNlEe38ZqOMrQdTdx8WunOPzVu1l5+WvIHe/kxz51C259mXLgMFD2OHX6HF+9834GBqoMDw+nsilKGQp3FHWI4hiNT6yU8aWybPJpfxSCDeiB7TB4MZ2xCfbc5DIyBPd+aY6T3/or5NnPo6J2djoT+BplVKplCUEIbhW8YZMphS3TnNmZM2hnojGv47TNTCQcuOSa+cFJCcLaLVdqetl0cdCMzveuif7TlnSW14uEjSkcdOMUyhuB0kZoWSZn1DKmXofoOEK7ypQJI8mbPvxRLt6xAXX2JK24Q+BKYhwefOgx/uIL/2AqZJGhY7lekGstdhCO0ZiTbgXh+DhuBVmq4FVqiPIY1eFLaIxezevfPsqBrz/PzH2/D2KAW3/kU1w1pejM1hkclAS+w+133s/JE6eo1YZYXasTKWwd3iXqNFGUiZQkFmXwaohgzPTVlydxBrcQTO6gMjXGwOaAKy+HN+3U/M8/XOX4A/+Me+6PiNr1AgnFtFj51lWWrbJlaLiE5SlUc9bgJe0z0FnO+HKp/owqDjkTmRiEEKarp1saNC+v7tI3WRMZbFeYgSIzuo7q2Ca/COGNWqC/iV56CVG72Ajit2cQsoOOWmhhgw8V0W7FXHTFtex577uZWFulXm8wNugQK8HZs2f4+h3/Rm1wiLDTQqXTIBz80iBRHBkoUnjEsUALz5w6fxTlDUPtcjpDVzB15VbeckONo4/McPCOv0W2X2Hghl/mxz9wCY1zZxnxFJ4jOXbsDN9+5FlcF8LQFE+UU8Of2IUKxnDDtmXHVHCFh1saQAoHLTz8cglRquIEqwQ0CI8JWmqIP354mCMP3IV36nOE9dVcMCwy1edEccoZALeGbp8yCKc3Cc1ZRGfWcN2kZxQq045UneHvZCoaaGVEHVU7BdZSYovICmAIuU70npx2kS+hJmqPYS6NCy2eu2zRohhkbFgwtsSaFFRMehkSSRffLXHDR36E6ZEKa8cO4xAShgrP8fn67XdwbmaGwaEhVuOYTmMVZBnp+dQbDdv6vAkZjBIpFxEMIqsbkdUp/NFNDF98MQMby/zAm2Df3pAnv/B3eI17CAdv4qOfvI1yuEar00b6krW1Fl/86iMsLi/jCJc41nRij7FdP0jcmuPsy183tYiwiVICHUU2UxBEyiemjBJlNBVwh8Gb4ml8nE2DOEd/j3BlxlTQVFy0mNI1NfI4BqeGcIfQasnUDFpnDdaRKnlKtHaMxDj2OsJPBQmwSlbGXWiLqLqWlJpA6lZt024gt6ctua8sR066Qga26paNtRL2w4y5GjAmPVxFOIbrpqM1lDCIVafZ4aob3sLuW76HkbkZZheXGBt0iWLJU08/y0MPP065UqXRaBFFIaWRHbQj6DQWqExeij95NXL0aqRbSomXro6QKkZ4TfzZfahmwF1zwzx+7wHk0u1Eq2vs+OgP8Y4bRjl79ATjQQfXKbHvwBkeeORxHAnSqdHo1BGjr6M6cRlP/cPvo1f2glvOhvtYFUvcsslKhEQIhSMEQrnQNooYauYc8dqcWfCcxqtJtyKEU0HICqgmorQJvCp0TloJ0mb2wKWfCi7ohOkqXGvhO0VChj9oCzNOTrveMafXDezECjOUwC1kdSInNFRoZsj02bXIDcFJhfNtQOFWTadoZ9b2rpWtUJ6J/ONYUR0Y4XUf+xmmZYdTrx5nbFDS6USsxBH/dvd9RLGi5AcoHRNrj+HLP8Hq819m5dTdNOrzyLNH0fobEEdZ00MUASVjBWQZ3FHQDjizOM0DqKn38fGP3EJrYZGy6NAJY1rtmHsefJq1lXlqtWHwqoTlaaavfT+HH/5rdPs00hMQL9txINlMtkSTLUmWVDrGi7RJI9OUySl0CAFEOH4NgglwIkT1EnR0zogl+iM2PpIW9WxkkLimOP7DqWY5u1OyvAdhKp86AqmsRZBms0ZNa6V1qvCfy+m6WDSJ0L3IDbJxfCOLEUZQGjB+x6mmXC2DvK0iGM6a5IG43eHSW7+fK3Zfhj71MipuU68Lhgcr7H3uGQ4cPIRfKtGJBJH2Gbnqo7TXlll+9WGkM0Bn+Swsn8viDOkYBmzSqhwlZVTjeoibxGzl+g/+GDumXWaPzLOlpvFch0efOcKTTz+PH1RpRw6xChje9T7i5iLzRx5FegK1upQTJBZFBS3Z9TMp1hHyI1cuNTm5X9lI2x01gsQjO2BxHkrTpjrYOIGI19AYQUJdmFxh8Xa3bLRxkwMqEzZNlPHi0yzOMQWaRL5Mq8ynp9U20TW3TNNbW1cCb+N1+ONbaRx6xFLlTC6oo1WDH8eh7ac2rUNRLBiZ3MLr3/NxBpYWOXV6hokhSRQr5mZnuP/+b5sUSRj1Cjl8NYNbbuaZL/0EwgPdXLHaKjm1jOTUCZETNhSpgJ/AI9j9YT7y4T2snD7HgKNZa4YgJbff/TCt+jLlgVGkW6UZXMmmTZfy3Jd+C+EL9NLJjCuwTtxTmF6lu8Z1iUR6V6RzYky3j49Tu5i4NQylafyNW+ksPY1yhhHxAiJaRXeWTGlbusaVEnXFVwrCOtofNq1jAnTYyYQa0nQttmrdRT0d2asuKIrC+MLOK3FKJuK07bHuhl1EzXqqPCFU26BKOjZ0nYwLbYM6yTW3fpyd27awcOIYUafJ4tIajhR8++EnOXbyrClgyBJtMcamK9/J4Uf+kri9iIgbJirthgjzQ3twskhWekbVy9/FOz/2IQb9NuHaGiqOUErx4GP7OXToCJ5v8uIluZPpN76PmRceoL1wBNE+nik1FXhvZEOFRMbASc25kEW+egqxWjUprQiqo8jSBrS/BTF6LaWqh2qsQvs0un7MsGQSxDKhqiV8OunaZ6ytSddmooRTMow8p2Tdql2H2GrQ6thA4nbhXQoiBFn+rfNJvmobrN2RaOEihKL57N+ALCH8qlF7kK4RCIjq9vXStDJJlzjSXHTF63j9u/4D4eI5Zs6cY6IGzXbEoSMneOrZl8zn+2N05DgjV7yf5dkjLBx5wGBA9bMmnUFdYJxYJh+m9CBTt/w4b7r5Il7ed4xhvYZbgXon4sFHn0XoGHfwYlZbNYLdb2LAh2eefhDprqDmj1pxft1HllwUBgAVyCdJd0m6GXM69UJC3KY6uoO2HINgC7WLr6bUug+aSwi5iI7ruTpHbNfBonbaECiF41rCa2BVpgPozKGjNYRTNdZQd3KCQzpbT3u2Zc9z03kxfJWZBhWbiNzuQuH5CFeaNibHR3i1Qu+URiCUOVme73PFrT/M8GCVV186hKNDVustfM/hgYeeYrVepzS4mdCbRmx+GwMj23jl0X9BVsdQq690qSGuMyI7Ne2eURyffA8f/ORtNBeWoLFmh4F5PPj0MU6fPo1fnaSlxuhseCPb91zBvrvuQLirsPyisRqFjhGZO7U5vZu0JOrn8AxZdI/SBlMqQrge3uhVtNgIta2MbxugefwVoG1EALFsJZ0rn9rPcyeuwLv4+8AfN2KB/jBUNhnUrj1vOI3RqmkcsQrXqfXWRcxesg6rSuS56znSnVZtdNxJJxWmIkVR06gdSg9hOWrCcdBRzPTuW7j6DbewfOQQ7eUFtFLEseLFlw5z/NQMleoEsrodMXE9F+15E4cf+TKxFtA8CvGa0VrrGV0pC4pRCVdcSEnsbGPXe3+E7Zslp4/NMxBAUPI4PbPKAw88iOeVoLSVNe8ytt3yWuqvHGD+1DFc9QqqNVOkIHdPWkpHkCSa9okGrpuN7JSlXJeKNmyiWFEZ30rkX07MOMElO6iJc6ycOYWwVBadDAvM9aNhqdvSq6Aac+bvwZihRmvb6ZIMVtBxdsLtgMB+1Cm3u8FBIAqjswsidMhUwDa5MZ0EO7aJEbdimJ7RKiqG8sgGXvuuH2JSNnn8pcMMBiGtjpHlePI7+/FLNbyRnXT8rUzf+FbqJ19h7sSruH6b6NxBC/pEXZLXdJna7JQLXNwrf4h3vWcPR146Cc0VFtoagctDTx2h0YLq8EVEA1dRvuw6poYFD3zxAG55iejQU3bB8lMf6TMHzo7wdkqZamMwaWoRqmVin85Sztw7IDW1LTewqLdBbQsbdtRoHXwO3V5FurZuruxYESGsBpSyCJtLZ/Zl8+n+IMQSHS3YjlUPEYyj23PWIkdWRy8nJtx1pGW+c0r0ALJ5Bo1KqdEJyKDjDtItm/cnm0G1TRDklkELtl73HnZcsZu9T+7Fo0kUxzQ7igPH1mjFAf7IlVDdycjuNzI24PD8vd/CmxxBzT5qzWx36bDLl5LNfJFSoCpX846PfpxA1VmeWcX3HAQxR2ckew8sUJm8BgZ3EW+6kj23DHPw/pfotBYRc/ejo06vec7Xu5PvLj0L0Ljm3LiDEIyjyxsMVqFjhMxQMK0dKhPbiAdvohONIbdsZGOtzvHnn0UEETqqI1TD+u2sCSLd7MJg9cLx0HELHa7Y2MkICOrOkm2VilKGk07K4H0Gecv1PKXIzURPdn7Wcx6b7qVErD/NQxPBmwgVhlQ3XMbu7/0QK6dPMHvmDArTSSqrm9h3ZBF3dBeMXofetIeLr57i2W8+igpGkStPoFrz2chMIYs+k9wiWPxZSBcthhm/+Se58boxXj00j0fI8kqDsYkNPHtwnk7k4Ixcjt5wHVteP4WYW+Xoi0uUxF7C2QNpRJz5cNEVgbtmIb1Bg6oJxyy+Pw7+lNF5BTvBwbHqkKYuPnTle1lub0aXBti8e4DO6VM05w4jqNukKYekCQ+tbPAljbiSlkGmGqU1xA2EVohoxbJqcoOAcoKHxQxTZ4uu6T+XXBf41DI172bQgDA96e0Fk/w7ASIBDCwp/8ob38XOzaO8/NyLSGL8oIyiyt5n9zE4tYVgy400h3dyyeunWTkxy+mjEaXSCTonHrGVJ90nkMpNj0hStIRYOPlWbvvYuzl8ZI5oeQGtIgaHhnj5pUPMLa0SbHk98cgOJnaNs3u74JF7FvEHV4mP3m4ebkEiW2YjOZNhfU7JuC8r360RpupWmoRw2UTQSfTtVu1EJ0Ft+3WEtbfQEeM4l2/h4k2Kg4/vQ3jKZECOaxU0HcvJz3rSBMri9M3cOC+VGeDkZ9LtIj7pPsO8RN686y6qrM5YmKJrErIweK7Q2swtU22z0+I2KuoYixDHDExfzWtvvpWXX3gRwjqDQ0M0lpe5/c67ePaZJ2gsriFLo1x10wgXb4558N5ZymMx0eF/tG1RKmdejV5r1tznFnJk6XgobxvX3faTbJgSnHjlHJWyx/hQwBMP3MvffuGvaZ49wPSmScqbRnnj9YIzLzdYaQb4C/9KuDyfcJiLpzuZsiw9s+B2JFh6APwRqGyHYBTcwNDBkxTN8QEPtzbJ2O4PsNycgPEpdl4bsPryPGtnjiOcyPALpJ/Wy0Uy3UFIKyg0bPvSsymSQlv5Nh2Z4BmRWpnukaWF0YA2rZX5Ibop6l4QmjURuiAz7Tol2ycBnY0Wdcu2xpbZc8t7cYOAo4eOMjo6zNzcKnfe+xitUFKdeiPnvD2sjY5y6XaHZ58JifwNuPP/l3DxuNVLLyoypxORhIeQJasUqW1d2qO2+0Pc+v27ePzxE0zWfDxCvv7l23n0yf1Up65hjms5tlJhz2scpsc0TxysUvOfpXHoXvBK6Vy0Yj9ZMolBoGUZjW8G+Dk+ojyNGNmDGNiRmmLDHZTgjSK8QbSuseX1t7EU7iZ0Bxi5usSlo5oXHnwR4S6jlZ3pquwYbuHmpmKU0N6wab7My3rbYUE6GRqkI4RqmwJMjq1UHIGZK5oLKxOquzWkkjGcRggrG1BrJbtMqdDJphZrjVYdpHTRsaJ20R5e87o38NTjLzA5OsCZ02d5+pm9yGAEVdtN+bI3cOkV03hLx/jrX3yRuhhkYuQYcy/faYoDdox1IUVL+GAyY4oKq6Omylfzzo9/nOXFOlUkpfAsX/7i7cwth5Qmrie66Hu49IaLmJqEhaOL/Om9MZWhMmsvfAHVaSGcuDAXVVgla51MXZS+qXvHDasQbZtAsM8kWrUtXS5Ut+N4AXG9weY9r8Pd+AMsny0jLhri+j0OB745S+fcy0g61qLF6Lhh25G1nf1m5deERLcs+dEpGTQuttz3hP+udabrR1YUSlvMu6Z6iHzKJvrFeQX1Z9WlPhxn/sQS7Q2dqsL3vfc2Zpc6lEWLuTOneG7fEWR5I9709zJ56ZUMhsc49X//jpkTZ8FZwwlPML+yz4gPEvfomSYdHiIZYZGOvnJRaoAtN/8wl2wfZf++c8Rn9/PFf7udtXgc/+K3MXjZa9iwycM/u5+9dxxkaa4DYoWqepr6iWfBsVUskY3USsaR4AyYh+jWTEmZ2HDV0abho7oFSmMQ1a2/H0BIQdxsMnbxZUy/5mM8dWIYb9rh6psleibm4FNHkM4Sqt2EcMGML0GAP2Hga3cQOisZQCNEbqBPyy64VZZKDmGawsaFMdx9+9mKU5X7jNDsM6ynd86nGU4rpUR1Yra99nvYeulunnn2EEunD/DsvuMEG25geMebGSvVWXr8f/PsgcfBdXHkMmrpAHFnOeWMpRwvrYubMO2aDVOJbiFcmHgTt7737cwvtFg7+Aj33fMQavAaxi97MxNTw+j5x3n14WdYPXcS/CaOOodefol6c9moHOjIxqlZVqCllSpxa5babWrfULL3UYNgClmdRAWT5jVIRPM0qrXC4LZN7Ln5LTx8fAo54jC9y+XqTYJ/+v/OIRsvm5SrdRahQ1O3cCrGvEdt41lUaCdyhQiSQpadv5pOa+yaR5MieN2NDqKoOyE0brJLdCFq72poTDVoVIFrZS5mukCFlDi1Lbzrto9w9OQcpw48yv7jbcYvfx9j48PUD32eAwcfIYpCpKehfpq4NZOlXnlqj3AtJyy/+aStONlgxJHE8Sg3vOMjbN8ecPsXvswTj7/M4M4fYHJsADX3ACeefIy1xXPgKaReRq+cIg7XLNIlMgnttM2YXPBmlJWJVg3HTzomsCpvh9pl4NfQzUVoLkJ5HCF9lD9Mdepibr75NTx6ahpVixm7zOXW6wR3fqVD88h+ZOuYITpGy2jdNrB2adrcR9wwFDQnsOBOJ6M0JzFUIaPSPUL/RcFP0WeQucgKLtmO6BrukSflJyOo8ugdAkc6xC3Bm77/fdRGN3LX7V/g1HKFzVe8AWf5aU7cfQeNlSVEUEZG8+j6vHUNbm6XdtkVt4qOWpnEtTXxZka6i4oFpS03cdv7r+erX/w2e1+K2X7FdcjlRznz7QeoryyCiBF6Fd1cNINrk9q4jqziRxeMK/w0atY2OtZxy2wAUTIb1B1ATl6Jbiyi105CWEeELZQ/xdDl13LL67bwxLFhmh4MbvF435vghe8ITjxyCKfzCnF7EaIlRDBqgJbyNuNKlp+3PejSBGVJn39y2PL1Bx1mEuvdUs4iGVaQ4692hXNukTAhspo62sqCde2cHEtEa42QAhXFDG68jHd8363807/+G0tqA5vGF5l/+jOszJ0Br4IUDdTaKRulypxKFcWoOU1XHJzyOFF7yRojo58uhLSnfDM/+p9+kO88d4b9Ly+zsfwSs089xtrSHIgOIl5BW65Z6q/zmHaKqYusfCwNHUpbJopRjSinaZB2qgivglo+bUCZ6jRSaWI5wMbXvI4b9mzm8SMu8zGM7ZDcdrPm9KuSR75yGrn6HKp+GFqnTQYUbAWxCJ15aJ6EzlyOdBplrjPB46WfBm6JfIruUzEppt5dBDgbnLsFXrvoNhM6U3+2wVuhxiwwC9Dy+MBHP86TL84ws9ggWHqA44efJlauGa7TOo1KNE7TnL+rLp7Qm50gixoEDIxuo7k2Q9xpIRwHKQVxE6575/fhD2/gns9/HjX3OK/OnAXVQKhliJp2sXM8gVQfJ3/CrSl3fKsGVTWBlFYI1TQuJuGTS9c0IfgTSEeihYN2a8Sj27ji2q1cvmOUb+9TNLRm/FKP979RsTon+dr/XUHOPouuH4DOrCFElCYQ0QK6dcoIJqZ9anE26hsBShpqdKremZAhXRN3pDJuujcY17lnrIvyYBlHTnSxQtKCg5N1uBTI9OC4PnGzw543fT/VqWu545++QPPEA6zMnkO4rhlcE4Z9AB6ZTYTIt1DpEPDBG0BitNriqM3I5DYaK3M0VuaJtWB44zY2jDp8/nP/jdVzr6Dbswi1hI6bNg0SPaSQ/HTnFM1LCI+ybAmHwvSORWuGnaoVAs+oYlZ3QGkUylPI0iChcvEvuZYbrp+k7JX4xtMgKpKx7YL/+BbN3FnJ3/9dE3nyBXTzCLozn6V1MoBoAcJ5i2tIKxrUb2JUPu9O5Ek6fdSddaEHvb8gRUKQEYHuGdYj7CTClAwg0u6KhPqDdNAKRiYv4WM/+nN8+V+/ytlXHkGFHQQtdNTuSvEoUnnSurHJvVP6kY6RbgWnNGqKFipEuAHVgSG0gpXFs3hBiVazCa0lhCuN8HCBl0/PXLZCkcaO90jLoklPtywZHF1H5qQLz6JuW8woEn8QJcowfAXbXreL1+0a4eBJzd6XNf6kw/Rl8LGbYP8hwb98cRV5bB96+Wl044hBzhLlDekh2qeM2nVsW77iRoZFpNrucW/QllpFnbPQ3VQu1SeK1/lhfIHuraTn+qDSRZPFUZXSRWiX697wvZyeWeLUy88g3Y6ZJdZ3emP2wIW0C2614wyPK+t9R0VIt4w3MG1r8k2QLr5fwi/VWF06YwbmJsK3eeXq7klGaaaRaw6walBCytzIax+8YdOJ6/jmdDsVRDAB0kWJCpQuZnDrlVxz0y4GqjWe2B+xsCJwphyuuE7zrmsFjz/t8u2vzCNOPoReec40fDieicy9GigHGkcRrSOGKRNboCVhDRfoa/lRoTm3qEVXIyPFAXx9ZtqLXNGl76IXxlflcXCZkw8TDo5XQgoIG6sIR5kRlaJ79kv+hJn+a5GAG/6IWfTWTG/vrDbtT0FtsylcRE3bOClw/RJxp02nsYCKmjnSv9urjZ5o2eZg3IyhihVPMAMDTezUMWpX3jDaraHFEJSnGNp+PVdefgljU5vYf0Rx+LSA4TLBNocbbxFcPia45980Rx44hjP3IGr1WdtibINHp2w170LckqR98mnTmBBZPTgdWaRT9yWvnE9AKIOq+whA9pmwbMdudg/ZEz2SlWmFq1vIRsWWpq36z2tLefKWOp1w7lIBPZWyPgpNFmlrfIRbnsAt1RBoVNyyWLfKdOviNnHYsiVNUaQ0JfJhVphY2w4RM6LLom9u2ahda42WgVGKkgPI2hY2XLSLS3buojIwwbFZOHhSo6jAxkEmd7u84UaH1hm4//Z52vv34jSfJl7bb4CXuGE56A5alCFcRKiWOfXhco682OnKwVXmTtebmVqgqBfna/WdrJzL0OyA3S6uWT7qK1CF8qM48+JEqo8vpbfqkwreZdJZIiXuqd7Tnpj7uI1wy3boXRWiFnHUSDFw6fi26hQTRy1U1CKOjEigWXTLY0sX2su00YVrUlN3APwq5eFpRjddzuTYJkZGJmjHJY7PCE7MAM4EDI4SXDrEVTd6bKnC3vsXOPr4flh8HNE5jO7M2KTBzFgT3oB1QxLiJWhaP55E43EHiKx0eoadF5+rXr+JNHW5+UJZf9UBE7yr7KSLwuSGLuuQNM0nhZgkXUhTBtU1oF0WzXsiJpi2ztoGvgSYSap1FjwRjpnCrFVxniha4wQ1nGDYoGPEdvSmGSog3RLSLeN6JRzXAylQUQetIrRSKDujzYxv8/H8CkFQplIdplodZHB0M44/xmozYG5Fc25F0W6VwJ+G4Yvwt02y/TUBG0dh7rmz7HtwP/rMY0h1ENWeM+lV8my8UYRfs67RjNzUa4fM1OVwNTPpiQlPNkFO6yfz530WXus+69qduum+rWoCfF0EX0T/0dNprpttglRrPNV610XuWlqTzplbFRUnMeo45cvrtEJEbsG7KkeWjSv9Gm55EtevorRK+7/NDjaVMekGOF4Zr1TB8zw8x9TePc/FcTxcLyDqdAhjl2bkUW+71NsBxCXwxiDYDKM7qV22jU07Awb9NquvHOfw488SnnoW9GFEPGdEF7QdFAjgjZiyaGfWVs9cdHMmnaemWzMQ54oqqB5zXUjV8tORu4fxiPW043RPoSVTBC349Fy02zXhp3iCc+iZVn1QIbrycdt25JQtAbCTEQatXJkhINh2JNXJ1BMK8li6kNqZxR9EBmNIbxDh+hbGtL3wWplWZqQJMqVrWbxurjfMNVrr3qTRzClP4wzupLTpKmrbpxmaEgStGeb37eXsi88Sz78CnECqBZStcQsLWpl4ITC9dOE5o/AoHBtr5AAiFZt570kbUm7Qb1E/RnWtRe8IJZ0z2/10Z0TXuDUbyfu6d7ie6LNrRHHh85ujGxAoMG7I6E4ysGZc5qpCWUZgWCnajPborhoV3EgefIjT9E96NZxgFBmYgbe4ZYOcqSilFmltdVuFRdicQUR1G25tI/7QNKI2glOKceMFOgtHaRx9mfbZw0Yc0WshaaGijgnUdG6UhjKZi/DH0LICrZOIJKXsMtVGA94EoIWR2MlBsB0pSYtkNs89/3hlNoGqX/DWrS6WG4DcZd7pDei6SnTFxgJ6e7sKuLbMLXrGzU7jgzjMTJiwPdsIs+gUs4FChVh3+zqR2wDWbzsVpFtD+IMIbwjhjyGcKlqWQJaNumQwiAwChCdxRB3dWSZaWyJaOYdurJnIWnYQMupj1VQSFKFlgPSHUEoh3AoiWjH8+RRHj/v0v8n+J1tTbDYpfGaWk6fx0QVMe8/PtTXvgu7CuzjPGOWc389ryXYN7TO+3Nbfk4g9R1ZI5TFUImDkGbKl8AqFB6NHqwt6OLqAVOX76PMQrOojsucWNyC5NFSRpXiOh3ASBWydzTBMZs0irOiwiWuEN2jUrjvL5uRGq1ZuvJ26qeJp1cVBCTkXJhKlTt0l9Ku7spp1zH7/hdcFDL4POEPRlGvVdcq7Fl/nULr8qUsKFbZ5IkMF81MjZEHwRKdpncy2oTVzhaunnO6uEZOF3vrcqSgIKIkindrep7BNDen9dcG4Qjj27bZnz9LHtDRjwnW4aogNaXHapGMJ+9Dcc9wViXelt+l3yscuuhjkCXpFHi+w8Plo3oRJuUUXPXRo0bWzxPpj0+0JMHPKRGGOt1axnQtULPRL+yDz/koImQ4NEo6XPiyRV0pMc1oLSNi5MdnGUqYEK7K25sQCKaUskJTvLZc28s73oiWl5lz9wYr0CukidRsVh3ZNVNpGlIgIFMilOrYxVGY1sIqTaV0srRGZaqe05l+pnEqk7hplns+w1jHxffRA+yFy/Xy76M33usdzJuI2UdSLAiEQnmfEhfP5ftQxlF7XzaLLTsO4Bt/PQBykiXijTg5WJdNhcfwsMk3dhjY98gVXlXTXSrvwOXH+OMr60xJ/61eM2ICFfw2ZQhjT3W5B4BqaWGx4BToKIWwjfC9nnlVaxEoHHoUte8+yV9w3+T22jaKO2xWsdadh3UF0Mc7pDbsKKZs+Tydod3leFKu31iT7pTI7d+xgoDaYM92axcUlDr58IGuC1OD5ZaavuI7FM2dYPncCPB8RR2y+Yg+NtWXmTxxIR2FoDeXaGFPbrkCLkmmgVLHZCypi9tgBOvWFdMEFMD65gS0XXUS5XEUpZYbmCXjl8CvMzpxLFa4RkkptjIktO9HuAEpHONIwXueP7ae+PJfOwU6GIQwMjrPtog28fOgYYauFGwjiMGJ8YpyBgQpHjxyxc2xUWqwyOgUa6fpcfvlOjh49QX1tKZXu1GlhxDzpTdObAcHpUydybjGdhdknpdbrCPv3Innuec16OtQtr/5gfia6xnSqKGTDhu18+1t3cOrUaRoNU0YMgoBHH3uSn/7p/4J0k5lmEh21mHjN93LJ63+EF37vw8wffIgr/+MfMfamd7Pv9z9oRoG4yQyyFrXpnUz/yOcI2y30wCY8KQgXT9PSDquf/zE6r5w1kxUcSdRc5j994mP80n/9z+x76QCe5xHHilLg8eu/+T/52lf+GccfQAnQnQZTu27h8p/7M1aOHUTh4xATyxITs4u89Mcfo7kyg5ACKSRxu801uy/l4W99hSe/8yLf9+4fZH7mDJKI//SJj/KOt97Mm9/0NpyghIrT1hEcxyFqrfGJT/wQn/+zP+DP/uJv+PFPfQo3qBJHGffPcR2i9gqf+fVfpdNu8VM/+Slcv2b19HIxi843ndLLlslP1xJFS+AWp/OtEwuI/rm46OJfuY7D3MISn/zxn2FufhkpTZXu1KmTpkSqs4cQ4fLU53+ZiXOKwff+b4aPPs7c5Jt46dfeQ3zqOwh/0IIaptQ5c+AJZn72DRAuUfv4l4jqbZpf+RHwBwyY4wY2hTKmuVKp8shjT/Bjn/oZhsaNpuzS4hznzs0hvCpxHFvuOqyGPi/sPcLs774RJQfQnTUq4xuofOoF9NgVsHAcgooNsiIGqgH79h/k4MH9PPTtO/gPH/g4Lz3/MFEY0urEPcUOQwtos2nLdn7jM7/Cz3z65/nPn/403/P2d3LfPXfg+FXiKC7EdK12SBgZEcDkv9Tnr4ui5AUUdNfQ3YI2rFinIkPPPK9CFCx0oV4L0G41WVyJ+Mxnf5Nm0wgCt5pNPv3pT9NcW0G6Ts5MRWhZZuXffhVduZnVDT+Mf9fHiE89hgimDCExhyIl7FhBSHs2JlpeApoIXUqLNXn3Njs3x2VXXsOf/tkfG4lur8QTjz/OZ/+fX0MGfpbvE9NcWqB1eprxd/+L6TaJJNp1WNy3j865veDkq4AxnU7IsdPzfPyjH+XXPvvf+dev/is/8J5bOXv2FMsrjbTjJ/G5UjjEcZ1f+qX/xsOPPsUf/eHnUHj84i/9Cg898E1iFRclP4GllbqZ5qQ1URSh47igZyMKVfK8LJzuBmB7LLjb88MeCq3uu610T3lPobTixOk5fuUX/jMz587g+z5KKxqNFtJ1DbExIWjEilKgGH/zXzFz8jjRU3+Od+1vMBi1WHn567Ygo3KlXWFFcCFeWkO3OkVsISVTxFYNy+Wb33qIX/q5n8EvGb56HLUJqhXanXYOBQuJOjHx2dOsPfu/IFyDS34Sb+xGxMNvR628Cp61Oo6BUZutFgvLLcq1CX7j13+B5/bu5bP/409YmDvLq8fP2jTVZq5CELdXuPq6W7ji6tfxoz90G44T8IW/+BNuvPntvO+Dn+Cf//6PkV7NQsfmfQvLTaQUlMtlvNIgKo7QStNoNk120FM+XceH29QuU/nKEyPzHLYcCnY+Y0IXqBNHEafOzvMTn/5lXImR6PZ8jhzaxx/8/n+35tSkWKWyy8T1/43Tc4p47ychXGatvUpp18/ix0t0Dj9q23ty8prJjNf2LLRWelEyneEAZ8+d44abN/Grv/F7BIFPGMeUK1X++R/+kvvv+TqOVyW2r43DDnpxH+LkXWbzzDxMfM0fUtn9C+hnf4Vwbc2wbOxntZotzpw5Rxi2cPxBbv/KP3Di+HF++v/3W5w4uS/DJixZxA8CPvzRT/Bnf/qHHDtyAC8YptVc4n//3m/wYz/9i3z7W3dw7uzpTGcXOHP6NK9/46380mf+GOm4KKVpNZf5w9//DPXV5H66bXKeQpUvjefCP0E/RK7fwq6T0CVz1u3rHcdhaHAAPwjStEkIQafTYWFxOfM1Glw/QPtjxCvHbNdIBaJF8CcRpTK6Pl8Y8Jfr1Ef4VauB00hTriLGoalUStQGKikDKNmgKyurNJrNlLOfYuFOgO6sWd012xxY24YbrxK16hY0spmc71IteywurYEQOI5L3FmlUh3E83xWVtcKC+J5HiMjg8ycO5fDA4xs6sTkOI1Gh3qjngOboVopUS6XClwGrWIWFxdRSvcVjOkRfER0aQKyTpWtTyrfH8/tYrKm5Mkoo1el77Gs0xxIkk5JFEHWq6Wx7UNk9fZudi5J/m05dj2b0O50Fds8vhuWdO1ccgrsH8Nw8YsgiGra+3O72EKWpmw7WkWawXSyQYUix2dRyrBjhJdDNm2pWLVspc8tMI0NfBv1OYAefUew5L5nZqO7WTMpQdrTma5Krz/IOiX6lE8L9OWkkzTfZar7uAGQwgjUmzgnby0suJLwc/MSpEnxRlPEqoWTDg5I6/wqsnvESmemvD6RuYC09Kt6x1yRBGDSomukEbTW2X32PJfUd+YXVqJzTR0CzNA96+91AiR1OWQh+qdSBfSyp6+wSwgyt4lEbjy6Pek6a1Xv18So+2PzPXh6T1zQzaNPTko7RbjSoTPSms84zPq005q6W4ha0xjVSpKmqhE6tvzxwAAqcXLySjnCQjKPNDc+tDArnOKMOixV2k6mSAYRpl0oibWx4sTmdZkkqGk5NqpXpqoYWVnP2DBtRLDOqq1XORM9wlBm4lOOftCF1SebI9kisvAQu1AdoXUvOpdDf3RhwSmS8vV6nC7Fzsuu5KJtO0BHDA0PUqpkD3LDpmk83wMdMzYxxabpLbh2vAZKZwI6FnnwpnfjTl4MKOTAGP6OmxBBxWigTl2Od9HrzInzSrjDG5CDk6Aj5MhmvO2vK25snRWOSuUye667gdrQEOiYjdNbuGrXNQgUQRCwcdM0GzZtxnEdAt9jeGQEUExtmGZyagOeb4R5pzZuolQuo3XE5i0XcdXuPaBjypUKV+66Ft/3ipuu74L3w1EyiRit8yJwutAhlFo2rdL1kv0DglzHRI97F/3tT197JIoQvtY4UvDGm27hkh2XgO6wY+dOpqenQXdwHYfbPvhhdu68DHSbjZs2cv2NNxJHdaR0cD23q7oU4135dmRtFFQLObUTuXUPcmgKVIjcfj14RvlRVIZxLrsZd/M1oDvIkY04V7wN4ZsBudLzM9+hOoyNjbFr9262X7wTdJvLrriCq/e8hmq1gkDxgQ//IO+/7QMQdxgZHWHX7t2g2uy6+mo+9JGPUS6XEER8/3tv48qrdoHqUK5U2bBxE+gOGzdt4vU33mSaO6TE89x1yuC9ZEdR+F+2afX6NMpC0cxByM+wLiIn+rBg+rUxi64esfWYOBopJIuLCzz3zLM2BnAZGxvj7NnTlMpVVldWWF5eZmVlmbXVVWZnZ1hbW0VKh/GxUeprazn3IYnX5ojOHLTTixXCKxGfe8XwyV0fKTTx8mlTDBnciJ47jG4sobVA46BmX8VxoDwyRlhftlU+89XK5SrHj71Kvb6GdHzarQ4njh9FIzh39gyvHD7I0tIKKg5ptUJWV1dYXVlmYWGZmXMmX2826iwvL7G8vES71WZxcYF6vWEqbFpz+vQppHQYGxtlbW01rTIWLet6TCbRS4le52VdgZ6n+/U09yy67h7fJXOND30KAKLPzaakv04mI54wQqVv/XvbEjC8THY8VWJQOXkxUjFiExUn/eZxjoTZyaQ80bYHzMkInjq07ck2Is9LmKk4e33epwsb4au29emBkQchyiYqEJmePCFsXJB8n4QC5mWvE372bKTsU0Tp17gg+sjE9IkB+o1qK0bv6y26oA/hKjcyW/TAscV7Ez2Lno7uLkToSTwnrN8mC0LyzQ+adTpe+2zrQtfmOm1OKaOnS747uRelsisLgcp9h27fm5BFhBBpLp19H134rsUgmCIlrW/1TNA3xO8uqxbGqHZPWhaJmqTXBeGK8wQQOfOtdX+otovNkQ6T0/1uct0Kz4XnxPUldmQsHt0XY9CG99ZtCmWQoX99hw13n7Zu/ED3OYyi57QVYzS9HuLVq7nTr1OlrzvWXS/TxT9nJ93VPeha34eaC8p6ukNzuykv65nks+kNyHVYHqIPfVd0fUdxXrJfP1ygSCXWQAl34x6EHACvhu6smprB6hHU6qtdWIXoSxbpRgf716jyzZR6HeraBbgrmgtuimJ6Rp8F7r5e+j5Pr+e21z31Qp5nAViHRdu3on+ebywuHBsIxwr7+Ybz7voIzzOn1imBVzV0ZKeEqJTRp55ATH4IecXPow7+EWJoD5S3o57+IO70xcRh1Uh6xXWI64aiHHcQkeXRdzoQtc24kmQaUj/X13fTnq8p4cKQ9/l2hEm4dVdf/joV01R+ROteqdCULJEDQvL9ZV3oVdrjLboAhCKjcR2/db6sgV7GqxC5+DLTo0fFZlqx1mZwj24bJUgl0G0NIiDe/zn08E7Qcwi/Sbz359Crx9F6B7rTyIYUxFbcJw4NqBJFxfGVffxOGkIkZUjd75mLrhKo6OPT9Xk2RO8p1wXeg8h+17qrHJ7SpTyd+V/Rh8Iu1vlwUfQ/QvS6+n47X+vvwo4VWaIiH/B0byrd3XDR1btdCIbK4DgIbwj3Pz2AevbviB/9HTMiK1zO5M17glld7NztsxD9WwD6+eGiqFMBPesXg+RAF92l9qf7iRLkZWS07ttpnPr0/AMt7kVR+HC97mSF9U6A5vwFHX0efn3/QK2nea/H117ANcUKMTSBbjaz/vC89dD5TaTP74P1BXhp+XXWuU4TugO+9cy+XpcOofvh7T1xQ99Vc3V/OnOfaP9CIM535Y0udPvdp12fx6eL/n9nHY5+PqBUsW1dzst80GeRxXk45X1SpkL94TwaARdqTDiv/+tN4QpFlnV8ec4bexqhkzJ3H5MmemnXQlzYH18wENF9JOd171TnbnJ/v03QnQqK9RZ8PdhY91n07+JXT4DWHYD2u6S+wJPrFgo7X6Cnexgy3017k+ybdnRHpEL03LdYd5n1Bdps1jP3OiPf9tWmXU/0YJ1aQN7EFXrfctZC667Sql6fO9Bno/f3JHrd9oHujpxe3ovulea/0IHvxkdSbbz1XKrOm/d+UCu95kKsk1r1NYait/HugrtXnCfdEL15Z59+ugwISvAHvQ7auM7JyPWs6Z5+ue7vpXuxiq64JItfVV/+Wq+kyIXcaVftXnP+tLgX8HH1d40O5EJ/kedV94vy+0ldnYehWbzz7yLAWy86FuuY8b7YQ/c82X7gVJ8sQcg+Efd5yqLrth5x4VhB5AiruZJpDw7T95n0cTtW/Udf0EfSZ2F1/tP1edLX79b/6/O8Xn8X11mHL9aVVq6LAPYs+oVAFfHvjwEuSGk6T5bCupH1ujIk5+HH9lv0fmE/vSZf9AkiRLfZEv8O0En8OzHJCyy8WC/z6JJDRa/LN7vwPazn4vQ68PI6aZ/oLwZ1wX3dl+Wk+5NYM/jW1eudsj7FPGvSdQ9tusf9rxOBf3dLKM4TtYh1qUP93cqFEEB9waLHee+l8Hl9TcT5LZYuJPHrlKp1f/DrAnDresdC0qe/UeTnqXcTpApwaHaSswBYr1/37xa40+eL9PX568T6PAvG+dIxfYHr9/vReSqP68lxFrKE8/na7pRlHU3XvNRtD2Ka/+P6G0Dno3fRIykr/h2e6zy7rG9GcB6F4nUswXrdl+dH4M5nhvV3EVTmgJzzVfd68vI+i6u/i7xdrJPp9Lz33xNb6L6c+P8/aZwYPIf5AFwAAAAASUVORK5CYII=";

#pragma mark - FluckAuthCore & ProxyPatchBytes Interception

@interface FluckAuthCoreHook : NSObject
@end

@implementation FluckAuthCoreHook

- (NSString *)hooked_savedKey {
    return [[NSUserDefaults standardUserDefaults] stringForKey:LICENSE_KEY_STORAGE];
}

- (NSString *)hooked_packageName {
    return @"External";
}

- (NSString *)hooked_expiryText {
    NSString *exp = [[NSUserDefaults standardUserDefaults] stringForKey:@"external.license.expiry"];
    if (!exp || exp.length == 0) {
        exp = [[NSUserDefaults standardUserDefaults] stringForKey:@"fluck.license.expiry"];
    }
    return (exp && exp.length > 0) ? exp : @"Active";
}

- (BOOL)hooked_gatePassed {
    NSString *key = [[NSUserDefaults standardUserDefaults] stringForKey:LICENSE_KEY_STORAGE];
    return (key && key.length > 0);
}

- (void)hooked_revokeGateWithReason:(id)reason {
    NSLog(@"[AuthGate] Neutralized legacy revokeGateWithReason: %@", reason);
}

- (void)hooked_revokeAndDie:(id)r label:(id)l {
    NSLog(@"[AuthGate] Neutralized legacy revokeAndDie");
}

- (void)hooked_failAndDie:(id)reason {
    NSLog(@"[AuthGate] Neutralized legacy failAndDie: %@", reason);
}

- (void)hooked_startKeyWatchdog {
    // Disabled in favor of SessionSecurityManager
}

- (void)hooked_startHeartbeat {
    // Disabled in favor of SessionSecurityManager
}

- (void)hooked_startPulse {
    // Disabled in favor of SessionSecurityManager
}

- (void)hooked_checkPackageWithCompletion:(void (^)(BOOL, id, id))completion {
    if (completion) {
        completion(YES, nil, nil);
    }
}

@end

@interface ProxyPatchBytesHook : NSObject
@end

@implementation ProxyPatchBytesHook

+ (NSData *)hooked_bytesForPatch:(NSString *)patchName {
    if (!patchName || patchName.length == 0) return nil;
    
    NSString *effectivePatch = patchName;
    if ([patchName isEqualToString:@"cache_drag"] || [patchName isEqualToString:@"drag"]) {
        effectivePatch = @"avatar_drag";
    }
    
    NSString *escapedPatch = [effectivePatch stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]];
    NSString *urlString = [NSString stringWithFormat:@"%@?patch=%@", BACKEND_BYTES_URL, escapedPatch];
    NSURL *url = [NSURL URLWithString:urlString];
    
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];
    [request setHTTPMethod:@"GET"];
    [request setTimeoutInterval:12.0];
    
    NSString *key = [[NSUserDefaults standardUserDefaults] stringForKey:LICENSE_KEY_STORAGE];
    if (key && key.length > 0) {
        [request setValue:key forHTTPHeaderField:@"X-License-Key"];
    }
    
    dispatch_semaphore_t sema = dispatch_semaphore_create(0);
    __block NSData *resultData = nil;
    
    NSURLSessionDataTask *task = [[NSURLSession sharedSession] dataTaskWithRequest:request completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
        if (!error && data && data.length > 100) {
            NSHTTPURLResponse *httpResp = (NSHTTPURLResponse *)response;
            if (httpResp.statusCode == 200) {
                resultData = data;
            }
        }
        dispatch_semaphore_signal(sema);
    }];
    [task resume];
    dispatch_semaphore_wait(sema, dispatch_time(DISPATCH_TIME_NOW, (int64_t)(12.0 * NSEC_PER_SEC)));
    
    if (resultData) {
        NSLog(@"[AuthGate] Successfully downloaded patch '%@' (%lu bytes) from backend server", patchName, (unsigned long)resultData.length);
    } else {
        NSLog(@"[AuthGate] Failed to fetch patch '%@' from backend server", patchName);
    }
    return resultData;
}

- (NSData *)instance_hooked_bytesForPatch:(NSString *)patchName {
    return [ProxyPatchBytesHook hooked_bytesForPatch:patchName];
}

@end

static void SwizzleInstance(Class targetClass, SEL origSel, Class hookClass, SEL hookSel) {
    if (!targetClass || !hookClass) return;
    Method orig = class_getInstanceMethod(targetClass, origSel);
    Method hook = class_getInstanceMethod(hookClass, hookSel);
    if (orig && hook) {
        method_setImplementation(orig, method_getImplementation(hook));
    }
}

static void SwizzleClassMethod(Class targetClass, SEL origSel, Class hookClass, SEL hookSel) {
    if (!targetClass || !hookClass) return;
    Method orig = class_getClassMethod(targetClass, origSel);
    Method hook = class_getClassMethod(hookClass, hookSel);
    if (orig && hook) {
        method_setImplementation(orig, method_getImplementation(hook));
    }
}

static void InstallAuthHooks(void) {
    Class coreClass = NSClassFromString(@"FluckAuthCore");
    if (coreClass) {
        SwizzleInstance(coreClass, NSSelectorFromString(@"savedKey"), [FluckAuthCoreHook class], @selector(hooked_savedKey));
        SwizzleInstance(coreClass, NSSelectorFromString(@"packageName"), [FluckAuthCoreHook class], @selector(hooked_packageName));
        SwizzleInstance(coreClass, NSSelectorFromString(@"expiryText"), [FluckAuthCoreHook class], @selector(hooked_expiryText));
        SwizzleInstance(coreClass, NSSelectorFromString(@"gatePassed"), [FluckAuthCoreHook class], @selector(hooked_gatePassed));
        SwizzleInstance(coreClass, NSSelectorFromString(@"revokeGateWithReason:"), [FluckAuthCoreHook class], @selector(hooked_revokeGateWithReason:));
        SwizzleInstance(coreClass, NSSelectorFromString(@"revokeAndDie:label:"), [FluckAuthCoreHook class], @selector(hooked_revokeAndDie:label:));
        SwizzleInstance(coreClass, NSSelectorFromString(@"failAndDie:"), [FluckAuthCoreHook class], @selector(hooked_failAndDie:));
        SwizzleInstance(coreClass, NSSelectorFromString(@"startKeyWatchdog"), [FluckAuthCoreHook class], @selector(hooked_startKeyWatchdog));
        SwizzleInstance(coreClass, NSSelectorFromString(@"startHeartbeat"), [FluckAuthCoreHook class], @selector(hooked_startHeartbeat));
        SwizzleInstance(coreClass, NSSelectorFromString(@"startPulse"), [FluckAuthCoreHook class], @selector(hooked_startPulse));
        SwizzleInstance(coreClass, NSSelectorFromString(@"checkPackageWithCompletion:"), [FluckAuthCoreHook class], @selector(hooked_checkPackageWithCompletion:));
        NSLog(@"[AuthGate] FluckAuthCore complete runtime swizzles installed successfully");
    }
    
    Class patchClass = NSClassFromString(@"ProxyPatchBytes");
    if (patchClass) {
        SwizzleClassMethod(patchClass, NSSelectorFromString(@"bytesForPatch:"), [ProxyPatchBytesHook class], @selector(hooked_bytesForPatch:));
        SwizzleInstance(patchClass, NSSelectorFromString(@"bytesForPatch:"), [ProxyPatchBytesHook class], @selector(instance_hooked_bytesForPatch:));
        NSLog(@"[AuthGate] ProxyPatchBytes live streaming swizzles installed successfully");
    }
}

#pragma mark - Unified VIP Dark Theme Engine

@interface VIPThemeManager : NSObject
+ (void)applyVIPThemeToViewController:(UIViewController *)vc;
+ (void)applyVIPThemeToView:(UIView *)rootView;
+ (void)applyVIPThemeToTabBar:(UITabBar *)tabBar;
+ (void)applyVIPThemeToImGuiMenu:(UIView *)menuView;
+ (void)removeModChestFromViewController:(UIViewController *)vc;
+ (void)installThemeHooks;
@end

@implementation VIPThemeManager

+ (UIColor *)colorObsidianBg {
    return [UIColor colorWithRed:0.06 green:0.07 blue:0.09 alpha:0.98];
}

+ (UIColor *)colorCardSlate {
    return [UIColor colorWithRed:0.11 green:0.13 blue:0.18 alpha:0.95];
}

+ (UIColor *)colorCardBorder {
    return [UIColor colorWithRed:0.22 green:0.28 blue:0.40 alpha:0.60];
}

+ (UIColor *)colorAccentBlue {
    return [UIColor colorWithRed:0.20 green:0.50 blue:0.95 alpha:1.0];
}

+ (UIColor *)colorCyanHighlight {
    return [UIColor colorWithRed:0.35 green:0.65 blue:1.0 alpha:1.0];
}

+ (UIColor *)colorTextPrimary {
    return [UIColor whiteColor];
}

+ (UIColor *)colorTextSecondary {
    return [UIColor colorWithRed:0.60 green:0.65 blue:0.75 alpha:1.0];
}

+ (UIColor *)colorInputContainer {
    return [UIColor colorWithRed:0.07 green:0.08 blue:0.12 alpha:0.95];
}

+ (void)applyVIPThemeToViewController:(UIViewController *)vc {
    if (!vc || !vc.isViewLoaded) return;
    
    if (@available(iOS 13.0, *)) {
        vc.overrideUserInterfaceStyle = UIUserInterfaceStyleDark;
    }
    
    // Setup Dark Background
    vc.view.backgroundColor = [self colorObsidianBg];
    
    // Check if background gradient already added
    BOOL hasGradient = NO;
    for (CALayer *sub in vc.view.layer.sublayers) {
        if ([sub isKindOfClass:[CAGradientLayer class]] && [sub.name isEqualToString:@"VIPGradient"]) {
            hasGradient = YES;
            sub.frame = vc.view.bounds;
            break;
        }
    }
    
    if (!hasGradient) {
        CAGradientLayer *gradient = [CAGradientLayer layer];
        gradient.name = @"VIPGradient";
        gradient.frame = vc.view.bounds;
        gradient.colors = @[
            (id)[UIColor colorWithRed:0.08 green:0.12 blue:0.20 alpha:1.0].CGColor,
            (id)[UIColor colorWithRed:0.04 green:0.05 blue:0.07 alpha:1.0].CGColor
        ];
        gradient.startPoint = CGPointMake(0.5, 0.0);
        gradient.endPoint = CGPointMake(0.5, 1.0);
        [vc.view.layer insertSublayer:gradient atIndex:0];
    }
    
    // Recursively theme all child elements
    [self applyVIPThemeToView:vc.view];
    
    // Apply tab and navigation bar titles
    NSString *className = NSStringFromClass([vc class]);
    if ([className containsString:@"NoExploit"]) {
        vc.title = @"Mods";
        vc.navigationItem.title = @"Mods";
        if (vc.tabBarItem) {
            vc.tabBarItem.title = @"Mods";
        }
    } else if ([className containsString:@"Exploit"]) {
        vc.title = @"Home";
        vc.navigationItem.title = @"Home";
        if (vc.tabBarItem) {
            vc.tabBarItem.title = @"Home";
        }
    }
    
    if (vc.tabBarController) {
        [self applyVIPThemeToTabBar:vc.tabBarController.tabBar];
    }
    if (vc.navigationController) {
        vc.navigationController.navigationBar.barTintColor = [self colorObsidianBg];
        vc.navigationController.navigationBar.tintColor = [self colorAccentBlue];
        vc.navigationController.navigationBar.titleTextAttributes = @{
            NSForegroundColorAttributeName: [self colorTextPrimary],
            NSFontAttributeName: [UIFont boldSystemFontOfSize:18.0]
        };
    }
}

+ (void)applyVIPThemeToView:(UIView *)rootView {
    if (!rootView) return;
    
    for (UIView *subview in rootView.subviews) {
        // 1. UISegmentedControl
        if ([subview isKindOfClass:[UISegmentedControl class]]) {
            UISegmentedControl *seg = (UISegmentedControl *)subview;
            seg.backgroundColor = [self colorInputContainer];
            if (@available(iOS 13.0, *)) {
                seg.selectedSegmentTintColor = [self colorAccentBlue];
            }
            seg.layer.cornerRadius = 10.0;
            seg.layer.borderWidth = 1.0;
            seg.layer.borderColor = [self colorCardBorder].CGColor;
            seg.clipsToBounds = YES;
            
            [seg setTitleTextAttributes:@{
                NSForegroundColorAttributeName: [self colorTextSecondary],
                NSFontAttributeName: [UIFont systemFontOfSize:13.0]
            } forState:UIControlStateNormal];
            
            [seg setTitleTextAttributes:@{
                NSForegroundColorAttributeName: [self colorTextPrimary],
                NSFontAttributeName: [UIFont boldSystemFontOfSize:13.0]
            } forState:UIControlStateSelected];
            continue;
        }
        
        // 2. UISwitch
        if ([subview isKindOfClass:[UISwitch class]]) {
            UISwitch *sw = (UISwitch *)subview;
            sw.onTintColor = [self colorAccentBlue];
            sw.thumbTintColor = [UIColor whiteColor];
            continue;
        }
        
        // 3. UIButton
        if ([subview isKindOfClass:[UIButton class]]) {
            UIButton *btn = (UIButton *)subview;
            NSString *title = [btn titleForState:UIControlStateNormal];
            
            if ([title isEqualToString:@"STOP"] || [title isEqualToString:@"START"]) {
                btn.backgroundColor = [self colorAccentBlue];
                [btn setTitleColor:[self colorTextPrimary] forState:UIControlStateNormal];
                btn.layer.cornerRadius = 10.0;
                btn.layer.shadowColor = [self colorAccentBlue].CGColor;
                btn.layer.shadowOffset = CGSizeMake(0, 3);
                btn.layer.shadowRadius = 8.0;
                btn.layer.shadowOpacity = 0.5;
            } else if ([title isEqualToString:@"Reset"] || [title containsString:@"Reset"]) {
                btn.backgroundColor = [self colorCardSlate];
                [btn setTitleColor:[self colorCyanHighlight] forState:UIControlStateNormal];
                btn.layer.cornerRadius = 10.0;
                btn.layer.borderWidth = 1.0;
                btn.layer.borderColor = [self colorCardBorder].CGColor;
            }
            continue;
        }
        
        // 4. UILabel
        if ([subview isKindOfClass:[UILabel class]]) {
            UILabel *lbl = (UILabel *)subview;
            NSString *txt = lbl.text;
            if (txt && (
                [txt containsString:@"sandbox escaped"] ||
                [txt containsString:@"patch bytes"] ||
                [txt containsString:@"unavailable"] ||
                [txt containsString:@"server/key"] ||
                [txt containsString:@"Enter your"]
            )) {
                lbl.textColor = [self colorTextSecondary];
            } else {
                lbl.textColor = [self colorTextPrimary];
            }
            continue;
        }
        
        // 5. Card Containers / Row Boxes
        if (subview.layer.cornerRadius > 0 && subview != rootView) {
            subview.backgroundColor = [self colorCardSlate];
            subview.layer.borderColor = [self colorCardBorder].CGColor;
            subview.layer.borderWidth = 1.0;
            subview.layer.shadowColor = [UIColor blackColor].CGColor;
            subview.layer.shadowOffset = CGSizeMake(0, 4);
            subview.layer.shadowRadius = 8.0;
            subview.layer.shadowOpacity = 0.35;
        }
        
        // Check for ImGui floating menu classes
        NSString *clsName = NSStringFromClass([subview class]);
        if ([clsName containsString:@"MenuUIView"] || [clsName containsString:@"MenuView"]) {
            [self applyVIPThemeToImGuiMenu:subview];
        }
        
        // Recurse down hierarchy
        [self applyVIPThemeToView:subview];
    }
}

+ (void)applyVIPThemeToTabBar:(UITabBar *)tabBar {
    if (!tabBar) return;
    
    // Rename tab items to Home, Mods, and ensure Account is preserved
    if (tabBar.items.count >= 3) {
        if ([tabBar.items[0].title isEqualToString:@"Exploit"] || tabBar.items[0].title.length == 0) {
            tabBar.items[0].title = @"Home";
        }
        if ([tabBar.items[1].title isEqualToString:@"No Exploit"] || tabBar.items[1].title.length == 0) {
            tabBar.items[1].title = @"Mods";
        }
        if (tabBar.items[2].title.length == 0 || [tabBar.items[2].title isEqualToString:@"Account"]) {
            tabBar.items[2].title = @"Account";
        }
    }
    
    tabBar.barTintColor = [self colorObsidianBg];
    tabBar.backgroundColor = [self colorObsidianBg];
    tabBar.tintColor = [self colorAccentBlue];
    tabBar.unselectedItemTintColor = [self colorTextSecondary];
    
    if (@available(iOS 13.0, *)) {
        UITabBarAppearance *appearance = [[UITabBarAppearance alloc] init];
        [appearance configureWithOpaqueBackground];
        appearance.backgroundColor = [self colorObsidianBg];
        
        appearance.stackedLayoutAppearance.selected.iconColor = [self colorAccentBlue];
        appearance.stackedLayoutAppearance.selected.titleTextAttributes = @{
            NSForegroundColorAttributeName: [self colorAccentBlue],
            NSFontAttributeName: [UIFont boldSystemFontOfSize:11.0]
        };
        appearance.stackedLayoutAppearance.normal.iconColor = [self colorTextSecondary];
        appearance.stackedLayoutAppearance.normal.titleTextAttributes = @{
            NSForegroundColorAttributeName: [self colorTextSecondary],
            NSFontAttributeName: [UIFont systemFontOfSize:11.0]
        };
        
        tabBar.standardAppearance = appearance;
        if (@available(iOS 15.0, *)) {
            tabBar.scrollEdgeAppearance = appearance;
        }
    }
}

+ (void)applyVIPThemeToImGuiMenu:(UIView *)menuView {
    if (!menuView) return;
    
    menuView.backgroundColor = [self colorCardSlate];
    menuView.layer.cornerRadius = 16.0;
    menuView.layer.borderWidth = 1.0;
    menuView.layer.borderColor = [self colorCardBorder].CGColor;
    menuView.layer.shadowColor = [UIColor blackColor].CGColor;
    menuView.layer.shadowOffset = CGSizeMake(0, 8);
    menuView.layer.shadowRadius = 16.0;
    menuView.layer.shadowOpacity = 0.6;
    
    // Style all child components of ImGui HUD
    for (UIView *child in menuView.subviews) {
        if ([child isKindOfClass:[UILabel class]]) {
            ((UILabel *)child).textColor = [self colorTextPrimary];
        } else if ([child isKindOfClass:[UISwitch class]]) {
            ((UISwitch *)child).onTintColor = [self colorAccentBlue];
        } else if ([child isKindOfClass:[UISlider class]]) {
            UISlider *sl = (UISlider *)child;
            sl.minimumTrackTintColor = [self colorAccentBlue];
            sl.thumbTintColor = [UIColor whiteColor];
        }
    }
}

+ (void)removeModChestFromViewController:(UIViewController *)vc {
    if (!vc || !vc.isViewLoaded) return;
    
    // Only process Exploit / NoExploit VCs
    NSString *className = NSStringFromClass([vc class]);
    if (![className containsString:@"Exploit"]) return;
    
    // Use tag 99887 to avoid double-processing
    static NSInteger kModChestProcessedTag = 99887;
    if (vc.view.tag == kModChestProcessedTag) return;
    
    // Find the scroll view (first UIScrollView child)
    UIScrollView *scrollView = nil;
    for (UIView *child in vc.view.subviews) {
        if ([child isKindOfClass:[UIScrollView class]]) {
            scrollView = (UIScrollView *)child;
            break;
        }
    }
    if (!scrollView) return;
    
    // The ModChest row lives inside aimContainer (or directly in scrollView)
    // We need to find it at any nesting depth within the scrollView
    __block UIView *modChestRow = nil;
    __block UIView *modChestParent = nil;
    __block CGFloat rowHeight = 0;
    
    // Recursive block to find ModChest row
    void (^__block findModChest)(UIView *parent);
    findModChest = ^(UIView *parent) {
        if (modChestRow) return; // already found
        for (UIView *child in parent.subviews) {
            if (child.hidden) continue;
            // Check if this view contains a UILabel with "ModChest"
            for (UIView *sub in child.subviews) {
                if ([sub isKindOfClass:[UILabel class]]) {
                    UILabel *lbl = (UILabel *)sub;
                    if ([lbl.text isEqualToString:@"ModChest"]) {
                        modChestRow = child;
                        modChestParent = parent;
                        rowHeight = child.frame.size.height + 8.0;
                        return;
                    }
                }
            }
            // Recurse into containers (but not UILabels, UIButtons, UISwitches)
            if (![child isKindOfClass:[UILabel class]] &&
                ![child isKindOfClass:[UIButton class]] &&
                ![child isKindOfClass:[UISwitch class]] &&
                child.subviews.count > 0) {
                findModChest(child);
            }
        }
    };
    
    findModChest(scrollView);
    
    if (!modChestRow || !modChestParent) return;
    
    CGFloat modChestY = modChestRow.frame.origin.y;
    
    // Hide the ModChest row
    modChestRow.hidden = YES;
    [modChestRow removeFromSuperview];
    
    // If ModChest was inside a container (aimContainer), shift rows within that container
    if (modChestParent != scrollView) {
        for (UIView *sibling in modChestParent.subviews) {
            if (sibling.hidden) continue;
            if (sibling.frame.origin.y > modChestY) {
                CGRect f = sibling.frame;
                f.origin.y -= rowHeight;
                sibling.frame = f;
            }
        }
    }
    
    // Shift everything below the container in scrollView upward
    // This moves the Reset button and status/result labels up
    // Find what's below aimContainer's bottom edge
    CGFloat containerBottomEdge = 0;
    if (modChestParent != scrollView) {
        containerBottomEdge = modChestParent.frame.origin.y + modChestParent.frame.size.height;
    } else {
        containerBottomEdge = modChestY;
    }
    
    for (UIView *sibling in scrollView.subviews) {
        if (sibling == modChestRow || sibling == modChestParent) continue;
        if (sibling.hidden) continue;
        // Shift elements below the container (or below the row if direct child)
        if (sibling.frame.origin.y >= containerBottomEdge - rowHeight) {
            CGRect f = sibling.frame;
            f.origin.y -= rowHeight;
            sibling.frame = f;
        }
    }
    
    // Shrink scroll content
    CGSize cs = scrollView.contentSize;
    cs.height -= rowHeight;
    scrollView.contentSize = cs;
    
    vc.view.tag = kModChestProcessedTag;
    NSLog(@"[AuthGate] ModChest row removed from %@, shifted Reset/Status up by %.0fpt", className, rowHeight);
}


+ (void)installThemeHooks {
    // 1. Enforce proxy.theme.mode = @"dark" in NSUserDefaults
    [[NSUserDefaults standardUserDefaults] setObject:@"dark" forKey:@"proxy.theme.mode"];
    [[NSUserDefaults standardUserDefaults] synchronize];
    
    [[NSNotificationCenter defaultCenter] postNotificationName:@"proxy.theme.changed" object:nil];
    
    // 2. Swizzle UIViewController viewWillAppear:
    Class vcClass = [UIViewController class];
    Method origMethod = class_getInstanceMethod(vcClass, @selector(viewWillAppear:));
    
    void (*orig_viewWillAppear)(id, SEL, BOOL) = (void (*)(id, SEL, BOOL))method_getImplementation(origMethod);
    
    IMP custom_viewWillAppear = imp_implementationWithBlock(^(id self, BOOL animated) {
        orig_viewWillAppear(self, @selector(viewWillAppear:), animated);
        
        NSString *className = NSStringFromClass([self class]);
        if ([className containsString:@"Exploit"] ||
            [className containsString:@"RootViewController"] ||
            [className containsString:@"HUD"] ||
            [className containsString:@"Proxy"]) {
            [VIPThemeManager applyVIPThemeToViewController:(UIViewController *)self];
            [VIPThemeManager removeModChestFromViewController:(UIViewController *)self];
        }
    });
    
    method_setImplementation(origMethod, custom_viewWillAppear);
    
    // 3. Strict Portrait Orientation Enforcement Across All ViewControllers
    Method origOrient = class_getInstanceMethod(vcClass, @selector(supportedInterfaceOrientations));
    if (origOrient) {
        IMP custom_supportedOrientations = imp_implementationWithBlock(^(id self) {
            return (UIInterfaceOrientationMask)UIInterfaceOrientationMaskPortrait;
        });
        method_setImplementation(origOrient, custom_supportedOrientations);
    }
    
    Method origRotate = class_getInstanceMethod(vcClass, @selector(shouldAutorotate));
    if (origRotate) {
        IMP custom_shouldAutorotate = imp_implementationWithBlock(^(id self) {
            return NO;
        });
        method_setImplementation(origRotate, custom_shouldAutorotate);
    }
    
    NSLog(@"[AuthGate] VIP Dark Theme Engine & Strict Portrait Locks successfully installed");
}

@end

#pragma mark - AuthGateViewController Interface

@interface AuthGateViewController : UIViewController <UITextFieldDelegate>

@property (nonatomic, strong) UIViewController *originalRootVC;
@property (nonatomic, strong) UIView *cardView;
@property (nonatomic, strong) UIImageView *logoImageView;
@property (nonatomic, strong) UILabel *titleLabel;
@property (nonatomic, strong) UILabel *subtitleLabel;
@property (nonatomic, strong) UITextField *keyField;
@property (nonatomic, strong) UIButton *pasteButton;
@property (nonatomic, strong) UIButton *activateButton;
@property (nonatomic, strong) UILabel *statusLabel;
@property (nonatomic, strong) UIButton *discordLinkBtn;
@property (nonatomic, strong) UIActivityIndicatorView *spinner;

- (void)openDiscordLink;

- (void)activateTapped:(id)sender;
- (void)pasteTapped:(id)sender;
- (void)finishAuthentication;

@end

#pragma mark - AuthGateViewController Implementation

@implementation AuthGateViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.view.backgroundColor = [VIPThemeManager colorObsidianBg];
    
    [self setupBackground];
    [self setupCardView];
    [self setupLogo];
    [self setupHeader];
    [self setupInputFields];
    [self setupButtons];
    [self setupStatusLabel];
    [self setupDiscordLink];
    
    UITapGestureRecognizer *tap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(dismissKeyboard)];
    [self.view addGestureRecognizer:tap];
    
    NSString *savedKey = [[NSUserDefaults standardUserDefaults] stringForKey:LICENSE_KEY_STORAGE];
    if (savedKey && savedKey.length > 0) {
        self.keyField.text = savedKey;
    }
}

- (void)dismissKeyboard {
    [self.view endEditing:YES];
}

- (void)setupBackground {
    CAGradientLayer *gradient = [CAGradientLayer layer];
    gradient.frame = self.view.bounds;
    gradient.colors = @[
        (id)[UIColor colorWithRed:0.08 green:0.12 blue:0.20 alpha:1.0].CGColor,
        (id)[UIColor colorWithRed:0.04 green:0.05 blue:0.07 alpha:1.0].CGColor
    ];
    gradient.startPoint = CGPointMake(0.5, 0.0);
    gradient.endPoint = CGPointMake(0.5, 1.0);
    [self.view.layer insertSublayer:gradient atIndex:0];
}

- (void)setupCardView {
    self.cardView = [[UIView alloc] init];
    self.cardView.translatesAutoresizingMaskIntoConstraints = NO;
    self.cardView.backgroundColor = [VIPThemeManager colorCardSlate];
    self.cardView.layer.cornerRadius = 22.0;
    self.cardView.layer.borderWidth = 1.0;
    self.cardView.layer.borderColor = [VIPThemeManager colorCardBorder].CGColor;
    
    self.cardView.layer.shadowColor = [UIColor blackColor].CGColor;
    self.cardView.layer.shadowOffset = CGSizeMake(0, 10);
    self.cardView.layer.shadowRadius = 25.0;
    self.cardView.layer.shadowOpacity = 0.5;
    
    [self.view addSubview:self.cardView];
    
    [NSLayoutConstraint activateConstraints:@[
        [self.cardView.centerXAnchor constraintEqualToAnchor:self.view.centerXAnchor],
        [self.cardView.centerYAnchor constraintEqualToAnchor:self.view.centerYAnchor constant:25.0],
        [self.cardView.widthAnchor constraintEqualToConstant:340.0],
        [self.cardView.heightAnchor constraintEqualToConstant:450.0]
    ]];
}

- (void)setupLogo {
    self.logoImageView = [[UIImageView alloc] init];
    self.logoImageView.translatesAutoresizingMaskIntoConstraints = NO;
    self.logoImageView.contentMode = UIViewContentModeScaleAspectFit;
    self.logoImageView.layer.cornerRadius = 16.0;
    self.logoImageView.layer.masksToBounds = YES;
    self.logoImageView.layer.borderWidth = 1.0;
    self.logoImageView.layer.borderColor = [UIColor colorWithRed:0.25 green:0.45 blue:0.85 alpha:0.50].CGColor;
    
    UIImage *logoImg = [UIImage imageNamed:@"external.png"] ?: [UIImage imageWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"external" ofType:@"png"]];
    if (!logoImg) {
        NSData *data = [[NSData alloc] initWithBase64EncodedString:kEmbeddedExternalLogoBase64 options:NSDataBase64DecodingIgnoreUnknownCharacters];
        if (data) {
            logoImg = [UIImage imageWithData:data];
        }
    }
    self.logoImageView.image = logoImg;
    [self.cardView addSubview:self.logoImageView];
    
    [NSLayoutConstraint activateConstraints:@[
        [self.logoImageView.topAnchor constraintEqualToAnchor:self.cardView.topAnchor constant:24.0],
        [self.logoImageView.centerXAnchor constraintEqualToAnchor:self.cardView.centerXAnchor],
        [self.logoImageView.widthAnchor constraintEqualToConstant:68.0],
        [self.logoImageView.heightAnchor constraintEqualToConstant:68.0]
    ]];
}

- (void)setupHeader {
    self.titleLabel = [[UILabel alloc] init];
    self.titleLabel.translatesAutoresizingMaskIntoConstraints = NO;
    self.titleLabel.text = @"ExternalFF Authentication";
    self.titleLabel.font = [UIFont boldSystemFontOfSize:18.5];
    self.titleLabel.textColor = [UIColor whiteColor];
    self.titleLabel.textAlignment = NSTextAlignmentCenter;
    [self.cardView addSubview:self.titleLabel];
    
    self.subtitleLabel = [[UILabel alloc] init];
    self.subtitleLabel.translatesAutoresizingMaskIntoConstraints = NO;
    self.subtitleLabel.text = @"Enter your subscription license key to access";
    self.subtitleLabel.font = [UIFont systemFontOfSize:12.5];
    self.subtitleLabel.textColor = [VIPThemeManager colorTextSecondary];
    self.subtitleLabel.textAlignment = NSTextAlignmentCenter;
    self.subtitleLabel.numberOfLines = 2;
    [self.cardView addSubview:self.subtitleLabel];
    
    [NSLayoutConstraint activateConstraints:@[
        [self.titleLabel.topAnchor constraintEqualToAnchor:self.logoImageView.bottomAnchor constant:12.0],
        [self.titleLabel.leadingAnchor constraintEqualToAnchor:self.cardView.leadingAnchor constant:16.0],
        [self.titleLabel.trailingAnchor constraintEqualToAnchor:self.cardView.trailingAnchor constant:-16.0],
        
        [self.subtitleLabel.topAnchor constraintEqualToAnchor:self.titleLabel.bottomAnchor constant:4.0],
        [self.subtitleLabel.leadingAnchor constraintEqualToAnchor:self.cardView.leadingAnchor constant:20.0],
        [self.subtitleLabel.trailingAnchor constraintEqualToAnchor:self.cardView.trailingAnchor constant:-20.0]
    ]];
}

- (void)setupInputFields {
    UIView *inputContainer = [[UIView alloc] init];
    inputContainer.translatesAutoresizingMaskIntoConstraints = NO;
    inputContainer.backgroundColor = [VIPThemeManager colorInputContainer];
    inputContainer.layer.cornerRadius = 12.0;
    inputContainer.layer.borderWidth = 1.0;
    inputContainer.layer.borderColor = [UIColor colorWithRed:0.20 green:0.25 blue:0.35 alpha:0.50].CGColor;
    [self.cardView addSubview:inputContainer];
    
    self.keyField = [[UITextField alloc] init];
    self.keyField.translatesAutoresizingMaskIntoConstraints = NO;
    self.keyField.placeholder = @"EFF-XXXX-XXXX-XXXX";
    self.keyField.attributedPlaceholder = [[NSAttributedString alloc] initWithString:self.keyField.placeholder
                                                                           attributes:@{NSForegroundColorAttributeName: [UIColor colorWithRed:0.45 green:0.50 blue:0.60 alpha:0.8]}];
    self.keyField.textColor = [UIColor whiteColor];
    self.keyField.font = [UIFont fontWithName:@"Menlo" size:14.0] ?: [UIFont systemFontOfSize:14.0];
    self.keyField.autocapitalizationType = UITextAutocapitalizationTypeAllCharacters;
    self.keyField.autocorrectionType = UITextAutocorrectionTypeNo;
    self.keyField.returnKeyType = UIReturnKeyDone;
    self.keyField.delegate = self;
    [inputContainer addSubview:self.keyField];
    
    self.pasteButton = [UIButton buttonWithType:UIButtonTypeSystem];
    self.pasteButton.translatesAutoresizingMaskIntoConstraints = NO;
    [self.pasteButton setTitle:@"PASTE" forState:UIControlStateNormal];
    self.pasteButton.titleLabel.font = [UIFont boldSystemFontOfSize:12.0];
    [self.pasteButton setTitleColor:[VIPThemeManager colorCyanHighlight] forState:UIControlStateNormal];
    [self.pasteButton addTarget:self action:@selector(pasteTapped:) forControlEvents:UIControlEventTouchUpInside];
    [inputContainer addSubview:self.pasteButton];
    
    [NSLayoutConstraint activateConstraints:@[
        [inputContainer.topAnchor constraintEqualToAnchor:self.subtitleLabel.bottomAnchor constant:24.0],
        [inputContainer.leadingAnchor constraintEqualToAnchor:self.cardView.leadingAnchor constant:20.0],
        [inputContainer.trailingAnchor constraintEqualToAnchor:self.cardView.trailingAnchor constant:-20.0],
        [inputContainer.heightAnchor constraintEqualToConstant:48.0],
        
        [self.keyField.leadingAnchor constraintEqualToAnchor:inputContainer.leadingAnchor constant:14.0],
        [self.keyField.centerYAnchor constraintEqualToAnchor:inputContainer.centerYAnchor],
        [self.keyField.trailingAnchor constraintEqualToAnchor:self.pasteButton.leadingAnchor constant:-8.0],
        
        [self.pasteButton.trailingAnchor constraintEqualToAnchor:inputContainer.trailingAnchor constant:-12.0],
        [self.pasteButton.centerYAnchor constraintEqualToAnchor:inputContainer.centerYAnchor],
        [self.pasteButton.widthAnchor constraintEqualToConstant:55.0]
    ]];
}

- (void)setupButtons {
    self.activateButton = [UIButton buttonWithType:UIButtonTypeSystem];
    self.activateButton.translatesAutoresizingMaskIntoConstraints = NO;
    [self.activateButton setTitle:@"ACTIVATE LICENSE" forState:UIControlStateNormal];
    self.activateButton.titleLabel.font = [UIFont boldSystemFontOfSize:15.0];
    [self.activateButton setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
    self.activateButton.backgroundColor = [VIPThemeManager colorAccentBlue];
    self.activateButton.layer.cornerRadius = 12.0;
    self.activateButton.layer.shadowColor = [VIPThemeManager colorAccentBlue].CGColor;
    self.activateButton.layer.shadowOffset = CGSizeMake(0, 4);
    self.activateButton.layer.shadowRadius = 10.0;
    self.activateButton.layer.shadowOpacity = 0.8;
    [self.activateButton addTarget:self action:@selector(activateTapped:) forControlEvents:UIControlEventTouchUpInside];
    [self.cardView addSubview:self.activateButton];
    
    self.spinner = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhite];
    self.spinner.translatesAutoresizingMaskIntoConstraints = NO;
    self.spinner.hidesWhenStopped = YES;
    [self.activateButton addSubview:self.spinner];
    
    [NSLayoutConstraint activateConstraints:@[
        [self.activateButton.topAnchor constraintEqualToAnchor:self.keyField.superview.bottomAnchor constant:20.0],
        [self.activateButton.leadingAnchor constraintEqualToAnchor:self.cardView.leadingAnchor constant:20.0],
        [self.activateButton.trailingAnchor constraintEqualToAnchor:self.cardView.trailingAnchor constant:-20.0],
        [self.activateButton.heightAnchor constraintEqualToConstant:50.0],
        
        [self.spinner.trailingAnchor constraintEqualToAnchor:self.activateButton.trailingAnchor constant:-16.0],
        [self.spinner.centerYAnchor constraintEqualToAnchor:self.activateButton.centerYAnchor]
    ]];
}

- (void)setupStatusLabel {
    self.statusLabel = [[UILabel alloc] init];
    self.statusLabel.translatesAutoresizingMaskIntoConstraints = NO;
    self.statusLabel.font = [UIFont systemFontOfSize:12.5];
    self.statusLabel.textColor = [VIPThemeManager colorTextSecondary];
    self.statusLabel.textAlignment = NSTextAlignmentCenter;
    self.statusLabel.numberOfLines = 2;
    [self.cardView addSubview:self.statusLabel];
    
    [NSLayoutConstraint activateConstraints:@[
        [self.statusLabel.topAnchor constraintEqualToAnchor:self.activateButton.bottomAnchor constant:16.0],
        [self.statusLabel.leadingAnchor constraintEqualToAnchor:self.cardView.leadingAnchor constant:16.0],
        [self.statusLabel.trailingAnchor constraintEqualToAnchor:self.cardView.trailingAnchor constant:-16.0]
    ]];
}

#pragma mark - Actions

- (void)setupDiscordLink {
    self.discordLinkBtn = [UIButton buttonWithType:UIButtonTypeSystem];
    self.discordLinkBtn.translatesAutoresizingMaskIntoConstraints = NO;
    
    NSMutableAttributedString *attrStr = [[NSMutableAttributedString alloc] initWithString:@"Don't have a key? " attributes:@{
        NSForegroundColorAttributeName: [UIColor colorWithRed:0.60 green:0.65 blue:0.75 alpha:1.0],
        NSFontAttributeName: [UIFont systemFontOfSize:12.5]
    }];
    [attrStr appendAttributedString:[[NSAttributedString alloc] initWithString:@"Get one here." attributes:@{
        NSForegroundColorAttributeName: [VIPThemeManager colorCyanHighlight],
        NSFontAttributeName: [UIFont boldSystemFontOfSize:12.5],
        NSUnderlineStyleAttributeName: @(NSUnderlineStyleSingle)
    }]];
    [self.discordLinkBtn setAttributedTitle:attrStr forState:UIControlStateNormal];
    [self.discordLinkBtn addTarget:self action:@selector(openDiscordLink) forControlEvents:UIControlEventTouchUpInside];
    [self.cardView addSubview:self.discordLinkBtn];
    
    [NSLayoutConstraint activateConstraints:@[
        [self.discordLinkBtn.topAnchor constraintEqualToAnchor:self.statusLabel.bottomAnchor constant:10.0],
        [self.discordLinkBtn.centerXAnchor constraintEqualToAnchor:self.cardView.centerXAnchor],
        [self.discordLinkBtn.heightAnchor constraintEqualToConstant:24.0]
    ]];
}

- (void)openDiscordLink {
    NSURL *url = [NSURL URLWithString:DISCORD_INVITE_URL];
    if ([[UIApplication sharedApplication] canOpenURL:url]) {
        if (@available(iOS 10.0, *)) {
            [[UIApplication sharedApplication] openURL:url options:@{} completionHandler:nil];
        } else {
            [[UIApplication sharedApplication] openURL:url];
        }
    }
}

- (void)pasteTapped:(id)sender {
    UIPasteboard *pasteboard = [UIPasteboard generalPasteboard];
    if (pasteboard.string && pasteboard.string.length > 0) {
        self.keyField.text = [pasteboard.string stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
        [self updateStatus:@"Key pasted from clipboard." isError:NO];
    } else {
        [self updateStatus:@"Clipboard is empty." isError:YES];
    }
}

- (BOOL)textFieldShouldReturn:(UITextField *)textField {
    [textField resignFirstResponder];
    [self activateTapped:nil];
    return YES;
}

- (void)activateTapped:(id)sender {
    [self.view endEditing:YES];
    
    NSString *rawKey = self.keyField.text;
    NSString *trimmedKey = [rawKey stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
    
    if (!trimmedKey || trimmedKey.length == 0) {
        [self updateStatus:@"Please enter your license key." isError:YES];
        return;
    }
    
    [self validateKeyWithServer:trimmedKey isAutoLogin:NO];
}

#pragma mark - Server Authentication Engine

- (void)setLoading:(BOOL)loading {
    if (loading) {
        [self.spinner startAnimating];
        self.activateButton.enabled = NO;
        self.activateButton.alpha = 0.8;
    } else {
        [self.spinner stopAnimating];
        self.activateButton.enabled = YES;
        self.activateButton.alpha = 1.0;
    }
}

- (void)updateStatus:(NSString *)message isError:(BOOL)isError {
    dispatch_async(dispatch_get_main_queue(), ^{
        self.statusLabel.text = message;
        if (isError) {
            self.statusLabel.textColor = [UIColor colorWithRed:1.0 green:0.35 blue:0.35 alpha:1.0];
        } else {
            self.statusLabel.textColor = [UIColor colorWithRed:0.35 green:0.85 blue:0.45 alpha:1.0];
        }
    });
}

- (void)validateKeyWithServer:(NSString *)key isAutoLogin:(BOOL)isAutoLogin {
    [self setLoading:YES];
    [self updateStatus:isAutoLogin ? @"Verifying saved license..." : @"Validating with authentication server..." isError:NO];
    
    NSString *udid = [[[UIDevice currentDevice] identifierForVendor] UUIDString] ?: @"IOS-DEVICE-1";
    NSString *appVer = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleShortVersionString"] ?: @"1.1";
    NSString *escapedKey = [key stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]];
    NSString *escapedUdid = [udid stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]];
    NSString *escapedVer = [appVer stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]];
    
    NSString *urlString = [NSString stringWithFormat:@"%@?license_key=%@&udid=%@&version=%@", BACKEND_SERVER_URL, escapedKey, escapedUdid, escapedVer];
    NSURL *url = [NSURL URLWithString:urlString];
    
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];
    [request setHTTPMethod:@"GET"];
    [request setTimeoutInterval:10.0];
    
    NSURLSessionDataTask *task = [[NSURLSession sharedSession] dataTaskWithRequest:request completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            [self setLoading:NO];
            
            if (error != nil || data == nil) {
                [self updateStatus:@"Server unreachable. Please check your connection." isError:YES];
                return;
            }
            
            NSHTTPURLResponse *httpResponse = (NSHTTPURLResponse *)response;
            NSString *responseString = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
            
            if (httpResponse.statusCode == 200 && responseString && ([responseString containsString:@"Nicchx"] || [responseString containsString:@"momo"])) {
                // Store license key
                [[NSUserDefaults standardUserDefaults] setObject:key forKey:LICENSE_KEY_STORAGE];
                [[NSUserDefaults standardUserDefaults] setObject:key forKey:@"fluck.license.key"];
                
                // Parse live expiry from server response
                id jsonObj = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
                if ([jsonObj isKindOfClass:[NSDictionary class]]) {
                    NSDictionary *dict = (NSDictionary *)jsonObj;
                    NSString *liveExpiry = dict[@"expiry"] ?: dict[@"expires_at"] ?: dict[@"fluck.license.expiry"];
                    if (liveExpiry && [liveExpiry isKindOfClass:[NSString class]] && liveExpiry.length > 0) {
                        [[NSUserDefaults standardUserDefaults] setObject:liveExpiry forKey:@"fluck.license.expiry"];
                        [[NSUserDefaults standardUserDefaults] setObject:liveExpiry forKey:@"external.license.expiry"];
                    }
                }
                [[NSUserDefaults standardUserDefaults] synchronize];
                
                Class coreClass = NSClassFromString(@"FluckAuthCore");
                if (coreClass) {
                    id sharedCore = [coreClass performSelector:NSSelectorFromString(@"shared")];
                    if (sharedCore && [sharedCore respondsToSelector:NSSelectorFromString(@"saveKey:")]) {
                        [sharedCore performSelector:NSSelectorFromString(@"saveKey:") withObject:key];
                    }
                    if (sharedCore && [sharedCore respondsToSelector:NSSelectorFromString(@"markGatePassed")]) {
                        [sharedCore performSelector:NSSelectorFromString(@"markGatePassed")];
                    }
                }
                
                [self updateStatus:@"Activated successfully! Launching..." isError:NO];
                
                dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.35 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                    [self finishAuthentication];
                });
            } else if (httpResponse.statusCode == 503) {
                [self updateStatus:@"Application is paused by administrator." isError:YES];
            } else if (httpResponse.statusCode == 426) {
                [self updateStatus:@"Newer version detected! Please contact owner." isError:YES];
            } else if (httpResponse.statusCode == 403) {
                [self updateStatus:@"License key has expired, is revoked, or bound to another device." isError:YES];
            } else if (httpResponse.statusCode == 401) {
                [self updateStatus:@"Invalid license key. Please check your key." isError:YES];
            } else {
                [self updateStatus:@"Application is paused by administrator." isError:YES];
            }
        });
    }];
    
    [task resume];
}

- (void)finishAuthentication {
    [UIView animateWithDuration:0.3 animations:^{
        self.view.alpha = 0.0;
        self.view.transform = CGAffineTransformMakeScale(1.05, 1.05);
    } completion:^(BOOL finished) {
        UIWindow *window = [UIApplication sharedApplication].keyWindow ?: [UIApplication sharedApplication].windows.firstObject;
        if (self.originalRootVC) {
            window.rootViewController = self.originalRootVC;
            [VIPThemeManager applyVIPThemeToViewController:self.originalRootVC];
        } else if (self.presentingViewController) {
            [self dismissViewControllerAnimated:NO completion:nil];
        }
        [self.view removeFromSuperview];
        [self removeFromParentViewController];
    }];
}

@end

#pragma mark - Live Session & Heartbeat Security Engine

@interface SessionSecurityManager : NSObject
+ (instancetype)shared;
- (void)startHeartbeatMonitor;
- (void)stopHeartbeatMonitor;
- (void)verifyLiveSessionNow;
- (void)handleSessionRevoked:(NSString *)reason;
@end

static void PresentAuthGate(void);

@implementation SessionSecurityManager {
    NSTimer *_heartbeatTimer;
    BOOL _isRevoked;
}

+ (instancetype)shared {
    static SessionSecurityManager *instance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        instance = [[SessionSecurityManager alloc] init];
    });
    return instance;
}

- (void)startHeartbeatMonitor {
    dispatch_async(dispatch_get_main_queue(), ^{
        [self stopHeartbeatMonitor];
        self->_isRevoked = NO;
        self->_heartbeatTimer = [NSTimer scheduledTimerWithTimeInterval:60.0
                                                                 target:self
                                                               selector:@selector(heartbeatTick)
                                                               userInfo:nil
                                                                repeats:YES];
        NSLog(@"[AuthGate Security] Live session heartbeat monitor started (Interval: 60s)");
    });
}

- (void)stopHeartbeatMonitor {
    if (_heartbeatTimer) {
        [_heartbeatTimer invalidate];
        _heartbeatTimer = nil;
    }
}

- (void)heartbeatTick {
    [self verifyLiveSessionNow];
}

- (void)verifyLiveSessionNow {
    NSString *key = [[NSUserDefaults standardUserDefaults] stringForKey:LICENSE_KEY_STORAGE];
    if (!key || key.length == 0) {
        [self handleSessionRevoked:@"No active license key found."];
        return;
    }
    
    NSString *udid = [[[UIDevice currentDevice] identifierForVendor] UUIDString] ?: @"IOS-DEVICE-1";
    NSString *appVer = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleShortVersionString"] ?: @"1.1";
    NSString *escapedKey = [key stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]];
    NSString *escapedUdid = [udid stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]];
    NSString *escapedVer = [appVer stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]];
    
    NSString *urlString = [NSString stringWithFormat:@"%@?license_key=%@&udid=%@&version=%@", BACKEND_SERVER_URL, escapedKey, escapedUdid, escapedVer];
    NSURL *url = [NSURL URLWithString:urlString];
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];
    [request setHTTPMethod:@"GET"];
    [request setTimeoutInterval:8.0];
    
    NSURLSessionDataTask *task = [[NSURLSession sharedSession] dataTaskWithRequest:request completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
        if (error || !data) {
            NSLog(@"[AuthGate Security] Heartbeat network check skipped (offline/unreachable).");
            return;
        }
        
        NSHTTPURLResponse *httpResp = (NSHTTPURLResponse *)response;
        NSString *respStr = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
        
        dispatch_async(dispatch_get_main_queue(), ^{
            if (httpResp.statusCode == 200 && respStr && ([respStr containsString:@"Nicchx"] || [respStr containsString:@"momo"])) {
                NSLog(@"[AuthGate Security] Live session heartbeat confirmed active.");
            } else if (httpResp.statusCode == 503) {
                [self handleSessionRevoked:@"Application paused by administrator."];
            } else if (httpResp.statusCode == 426) {
                [self handleSessionRevoked:@"Newer version detected! Update required."];
            } else if (httpResp.statusCode == 403) {
                [self handleSessionRevoked:@"License expired, revoked, or bound to another device."];
            } else {
                [self handleSessionRevoked:@"Session authorization rejected by server."];
            }
        });
    }];
    [task resume];
}

- (void)handleSessionRevoked:(NSString *)reason {
    if (_isRevoked) return;
    _isRevoked = YES;
    
    NSLog(@"[AuthGate Security] CRITICAL: Session Revocation Triggered: %@", reason);
    [self stopHeartbeatMonitor];
    
    // Clear saved licenses
    [[NSUserDefaults standardUserDefaults] removeObjectForKey:LICENSE_KEY_STORAGE];
    [[NSUserDefaults standardUserDefaults] removeObjectForKey:@"fluck.license.key"];
    [[NSUserDefaults standardUserDefaults] removeObjectForKey:@"external.license.expiry"];
    [[NSUserDefaults standardUserDefaults] synchronize];
    
    // Present Lock Screen
    PresentAuthGate();
}

@end

#pragma mark - Safe Presentation Hook

static void PresentAuthGate(void) {
    dispatch_async(dispatch_get_main_queue(), ^{
        UIWindow *window = [UIApplication sharedApplication].keyWindow ?: [UIApplication sharedApplication].windows.firstObject;
        if (!window || !window.rootViewController) {
            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                PresentAuthGate();
            });
            return;
        }
        
        UIViewController *currentRoot = window.rootViewController;
        if ([currentRoot isKindOfClass:[AuthGateViewController class]]) {
            return;
        }
        
        AuthGateViewController *authVC = [[AuthGateViewController alloc] init];
        authVC.originalRootVC = currentRoot;
        window.rootViewController = authVC;
    });
}

__attribute__((constructor))
static void AuthGateInitialize(void) {
    NSLog(@"[AuthGate] Dynamic Library Loaded Successfully");
    
    InstallAuthHooks();
    [VIPThemeManager installThemeHooks];
    
    [[NSNotificationCenter defaultCenter] addObserverForName:UIApplicationDidFinishLaunchingNotification
                                                      object:nil
                                                       queue:[NSOperationQueue mainQueue]
                                                  usingBlock:^(NSNotification * _Nonnull note) {
        PresentAuthGate();
        if ([[NSUserDefaults standardUserDefaults] stringForKey:LICENSE_KEY_STORAGE]) {
            [[SessionSecurityManager shared] startHeartbeatMonitor];
        }
    }];
}
